Woah sick

In [2]:
!pip install pyspark pyarrow

WARNING: The directory '/home/jovyan/.cache/pip' or its parent directory is not owned or is not writable by the current user. The cache has been disabled. Check the permissions and owner of that directory. If executing pip with sudo, you should use sudo's -H flag.
Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: pyspark in /usr/local/spark/python (3.5.0)
Requirement already satisfied: pyarrow in /opt/conda/lib/python3.11/site-packages (13.0.0)
Requirement already satisfied: py4j==0.10.9.7 in /home/tragus/.local/lib/python3.11/site-packages (from pyspark) (0.10.9.7)
Requirement already satisfied: numpy>=1.16.6 in /opt/conda/lib/python3.11/site-packages (from pyarrow) (1.24.4)

In [3]:
import os
print(os.getcwd())

/expanse/lustre/projects/uci157/tragus

In [4]:
from pyspark.sql import SparkSession
from pyspark.sql.types import StructType, StructField, IntegerType, StringType, LongType, DoubleType, FloatType
from pyspark.sql.functions import col, count, length,countDistinct, min as spark_min, max as spark_max,avg, stddev, approx_count_distinct

spark = (SparkSession.builder.appName("MusicBrainz").config("spark.driver.memory", "2g").config("spark.executor.memory", "18g").config('spark.executor.instances', 7).getOrCreate())

I saw on Piazza somebody was asking about the Spark Jobs UI, and apparently I was right that this is something distinct from the Expanse Jobs page. Apparently it's this-

Not sure how to get it to display the active number of tasks since it's not live

In [5]:
import requests
import pandas as pd

# Get the active Spark Context and URL
sc = spark.sparkContext
url = f"{sc.uiWebUrl}/api/v1/applications/{sc.applicationId}/executors"

# Fetch the executor data from the API
response = requests.get(url)
executors = response.json()

# Format into a readable DataFrame
spark_df = pd.DataFrame(executors)[['id', 'totalCores', 'maxMemory', 'activeTasks', 'isActive']]
spark_df['maxMemory_GB'] = (spark_df['maxMemory'] / (1024**3)).round(2)
spark_df

       id  totalCores   maxMemory  activeTasks  isActive  maxMemory_GB
0  driver           8  1099746508            0      True          1.02

In [6]:
MBDUMP = "musicbrainz_project/raw_data/mbdump"

In [7]:
def peek(df, n=20):
    return display(df.limit(n).toPandas())

# DEFINE SCHEMAS

In [8]:
artist_schema = StructType([
    StructField("id",               IntegerType(),   True),
    StructField("gid",              StringType(),    True),
    StructField("name",             StringType(),    True),
    StructField("sort_name",        StringType(),    True),
    StructField("begin_date_year",  IntegerType(),   True),
    StructField("begin_date_month", IntegerType(),   True),
    StructField("begin_date_day",   IntegerType(),   True),
    StructField("end_date_year",    IntegerType(),   True),
    StructField("end_date_month",   IntegerType(),   True),
    StructField("end_date_day",     IntegerType(),   True),
    StructField("type",             IntegerType(),   True),
    StructField("area",             IntegerType(),   True),
    StructField("gender",           IntegerType(),   True),
    StructField("comment",          StringType(),    True),
    StructField("edits_pending",    IntegerType(),   True),
    StructField("last_updated",     StringType(),    True),
    StructField("ended",            StringType(),    True),
    StructField("begin_area",       IntegerType(),   True),
    StructField("end_area",         IntegerType(),   True),
])
instrument_schema = StructType([
    StructField("id",            IntegerType(), True),
    StructField("gid",           StringType(),  True),
    StructField("name",          StringType(),  True),
    StructField("type",          IntegerType(), True),
    StructField("edits_pending", IntegerType(), True),
    StructField("last_updated",  StringType(),  True),
    StructField("comment",       StringType(),  True),
    StructField("description",   StringType(),  True),
])
label_schema = StructType([
    StructField("id",                IntegerType(), True),
    StructField("gid",               StringType(),  True),
    StructField("name",              StringType(),  True),
    StructField("begin_date_year",   IntegerType(), True),
    StructField("begin_date_month",  IntegerType(), True),
    StructField("begin_date_day",    IntegerType(), True),
    StructField("end_date_year",     IntegerType(), True),
    StructField("end_date_month",    IntegerType(), True),
    StructField("end_date_day",      IntegerType(), True),
    StructField("label_code",        IntegerType(), True),
    StructField("type",              IntegerType(), True),
    StructField("area",              IntegerType(), True),
    StructField("comment",           StringType(),  True),
    StructField("edits_pending",     IntegerType(), True),
    StructField("last_updated",      StringType(),  True),
    StructField("ended",             StringType(),  True),
])
genre_schema = StructType([
    StructField("id",            IntegerType(), True),
    StructField("gid",           StringType(),  True),
    StructField("name",          StringType(),  True),
    StructField("comment",       StringType(),  True),
    StructField("edits_pending", IntegerType(), True),
    StructField("last_updated",  StringType(),  True),
])
area_schema = StructType([
    StructField("id",               IntegerType(), True),
    StructField("gid",              StringType(),  True),
    StructField("name",             StringType(),  True),
    StructField("type",             IntegerType(), True),
    StructField("edits_pending",    IntegerType(), True),
    StructField("last_updated",     StringType(),  True),
    StructField("begin_date_year",  IntegerType(), True),
    StructField("begin_date_month", IntegerType(), True),
    StructField("begin_date_day",   IntegerType(), True),
    StructField("end_date_year",    IntegerType(), True),
    StructField("end_date_month",   IntegerType(), True),
    StructField("end_date_day",     IntegerType(), True),
    StructField("ended",            StringType(),  True),
    StructField("comment",          StringType(),  True),
])
tag_schema = StructType([
    StructField("id",            IntegerType(), True),
    StructField("name",          StringType(),  True),
    StructField("ref_count",     IntegerType(), True),
])
gender_schema = StructType([
    StructField("id",   IntegerType(), True),
    StructField("name", StringType(),  True),
])
release_group_schema = StructType([
    StructField("id",            IntegerType(), True),
    StructField("gid",           StringType(),  True),
    StructField("title",         StringType(),  True),
    StructField("artist_credit", IntegerType(), True),
    StructField("type",          IntegerType(), True),
    StructField("comment",       StringType(),  True),
    StructField("edits_pending", IntegerType(), True),
    StructField("last_updated",  StringType(),  True),
])
l_artist_label_schema = StructType([
    StructField("id",             IntegerType(), True),
    StructField("link",           IntegerType(), True),
    StructField("entity0",        IntegerType(), True),  # artist
    StructField("entity1",        IntegerType(), True),  # label
    StructField("edits_pending",  IntegerType(), True),
    StructField("last_updated",   StringType(),  True),
    StructField("link_order",     IntegerType(), True),
    StructField("entity0_credit", StringType(),  True),
    StructField("entity1_credit", StringType(),  True),
])
l_artist_release_group_schema = StructType([
    StructField("id",             IntegerType(), True),
    StructField("link",           IntegerType(), True),
    StructField("entity0",        IntegerType(), True),  # artist
    StructField("entity1",        IntegerType(), True),  # release_group
    StructField("edits_pending",  IntegerType(), True),
    StructField("last_updated",   StringType(),  True),
    StructField("link_order",     IntegerType(), True),
    StructField("entity0_credit", StringType(),  True),
    StructField("entity1_credit", StringType(),  True),
])
label_tag_schema = StructType([
    StructField("label",        IntegerType(), True),
    StructField("tag",          IntegerType(), True),
    StructField("count",        IntegerType(), True),
    StructField("last_updated", StringType(),  True),
])
l_artist_genre_schema = StructType([
    StructField("id",             IntegerType(), True),
    StructField("link",           IntegerType(), True),
    StructField("entity0",        IntegerType(), True),  # artist
    StructField("entity1",        IntegerType(), True),  # genre
    StructField("edits_pending",  IntegerType(), True),
    StructField("last_updated",   StringType(),  True),
    StructField("link_order",     IntegerType(), True),
    StructField("entity0_credit", StringType(),  True),
    StructField("entity1_credit", StringType(),  True),
])
l_artist_artist_schema = StructType([
    StructField("id",      IntegerType(), True),
    StructField("link",    IntegerType(), True),
    StructField("entity0", IntegerType(), True),
    StructField("entity1", IntegerType(), True),
])
release_group_tag_schema = StructType([
    StructField("release_group", IntegerType(), True),
    StructField("tag",           IntegerType(), True),
    StructField("count",         IntegerType(), True),
    StructField("last_updated",  StringType(),  True),
])
artist_tag_schema = StructType([
    StructField("artist",       IntegerType(), True),
    StructField("tag",          IntegerType(), True),
    StructField("count",        IntegerType(), True),
    StructField("last_updated", StringType(),  True),
])
artist_credit_schema = StructType([
    StructField("id",            IntegerType(), True),
    StructField("name",          StringType(),  True),
    StructField("artist_count",  IntegerType(), True),
    StructField("ref_count",     IntegerType(), True),
    StructField("created",       StringType(),  True),
    StructField("edits_pending", IntegerType(), True),
    StructField("gid",           StringType(),  True),
])
artist_credit_name_schema = StructType([
    StructField("artist_credit", IntegerType(), True),
    StructField("position",      IntegerType(), True),
    StructField("artist",        IntegerType(), True),
    StructField("name",          StringType(),  True),
    StructField("join_phrase",   StringType(),  True),
])
l_artist_instrument_schema = StructType([
    StructField("id",             IntegerType(), True),
    StructField("link",           IntegerType(), True),
    StructField("entity0",        IntegerType(), True),  # artist
    StructField("entity1",        IntegerType(), True),  # instrument
    StructField("edits_pending",  IntegerType(), True),
    StructField("last_updated",   StringType(),  True),
    StructField("link_order",     IntegerType(), True),
    StructField("entity0_credit", StringType(),  True),
    StructField("entity1_credit", StringType(),  True),
])
link_schema = StructType([
    StructField("id",                IntegerType(), True),
    StructField("link_type",         IntegerType(), True),
    StructField("begin_date_year",   IntegerType(), True),
    StructField("begin_date_month",  IntegerType(), True),
    StructField("begin_date_day",    IntegerType(), True),
    StructField("end_date_year",     IntegerType(), True),
    StructField("end_date_month",    IntegerType(), True),
    StructField("end_date_day",      IntegerType(), True),
    StructField("attribute_count",   IntegerType(), True),
    StructField("created",           StringType(),  True),
    StructField("ended",             StringType(),  True),
])
link_type_schema = StructType([
    StructField("id",                  IntegerType(), True),
    StructField("parent",              IntegerType(), True),
    StructField("child_order",         IntegerType(), True),
    StructField("gid",                 StringType(),  True),
    StructField("entity_type0",        StringType(),  True),
    StructField("entity_type1",        StringType(),  True),
    StructField("name",                StringType(),  True),
    StructField("description",         StringType(),  True),
    StructField("link_phrase",         StringType(),  True),
    StructField("reverse_link_phrase", StringType(),  True),
    StructField("long_link_phrase",    StringType(),  True),
    StructField("last_updated",        StringType(),  True),
    StructField("is_deprecated",       StringType(),  True),
    StructField("has_dates",           StringType(),  True),
    StructField("attribute_count",     IntegerType(), True),
    StructField("priority",            IntegerType(), True),
])

So the schema definitely aren't perfect - after testing out some SQL queries it becomes clear some of variables aren't assigned to the right columns. I think it will take some trial and error to suss out which variables are assigned correctly. It's a really great start though!! I've adjusted a couple and I'll spend a little more time experimenting with SQL to improve it

Something to be aware of is that a lot of these schema don't have all of the columns present in the TSV. We can still create the dataframes bc if there are extra columns without assignment in the schema, Spark just ignores them. Usually the variables we care about appear in the first half of the dataframe so ... maybe not so important but just FYI

### update:
it turns out we were missing some important tables, link and link_type. All "l_" tables have a link column which contains a code that determines the type of relationship being described in that row, and the link table connects to "link_type" which has more in-depth metadata on the particular relationship.

# BUILD TABLES

In [9]:
schemas = {
    "artist": artist_schema,
    "instrument": instrument_schema,
    "label": label_schema,
    "genre": genre_schema,
    "area": area_schema,
    "tag": tag_schema,
    "gender": gender_schema,
    "release_group": release_group_schema,
    "l_artist_label": l_artist_label_schema,
    "l_artist_release_group": l_artist_release_group_schema,
    "label_tag": label_tag_schema,
    "l_artist_genre": l_artist_genre_schema,
    "l_artist_artist": l_artist_artist_schema,
    "release_group_tag": release_group_tag_schema,
    "artist_tag": artist_tag_schema,
    "artist_credit": artist_credit_schema,
    "artist_credit_name": artist_credit_name_schema,
    "l_artist_instrument": l_artist_instrument_schema,
    "link": link_schema,
    "link_type": link_type_schema,
}

dfs = {}
profile_rows = []

for table_name, schema in schemas.items():
    df = (
        spark.read
        .option("sep", "\t")
        .option("nullValue", r"\N")
        .option("header", "false")
        .option("quote", "")
        .option("escape", "")
        .schema(schema)
        .csv(f"{MBDUMP}/{table_name}")
    )

    dfs[table_name] = df

    print(f"=== PEEK: {table_name} ===")
    peek(df)

=== PEEK: artist ===

,id,gid,name,sort_name,begin_date_year,begin_date_month,begin_date_day,end_date_year,end_date_month,end_date_day,type,area,gender,comment,edits_pending,last_updated,ended,begin_area,end_area
0,2252039,fadeb38c-833f-40bc-9d8c-a6383b38b1be,Доктор Сатана,Доктор Сатана,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None,0,2021-11-23 07:08:52.479537+00,f,NaN,NaN
1,371203,49add228-eac5-4de8-836c-d75cde7369c3,Pete Moutso,"Moutso, Pete",NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN,NaN,None,0,None,f,NaN,NaN
2,3087346,dfdce491-133d-4e9f-9e48-795587e181b0,UNlT,UNlT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None,0,2025-09-14 23:53:28.004798+00,f,NaN,NaN
3,2851271,165a49a0-2b3b-4078-a3c1-905afdc07c0a,Babyglock,Babyglock,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None,0,2024-10-19 03:33:55.474151+00,f,NaN,NaN
4,145773,7b4a548e-a01a-49b7-82e7-b49efeb9732c,Aric Leavitt,"Leavitt, Aric",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None,0,None,f,NaN,NaN
5,1076328,60aca66f-e91a-4cb5-9308-b6e293cd833e,Fonograff,Fonograff,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None,0,2014-01-10 16:25:20.992213+00,f,NaN,NaN
6,1172876,3e1bd546-d2a7-49cb-b38d-d70904a1d719,Al Street,"Street, Al",NaN,NaN,NaN,NaN,NaN,NaN,1.0,222.0,1.0,None,0,2014-11-23 14:07:19.782509+00,f,NaN,NaN
7,220155,df120895-f6c6-4a66-b9cf-73350f0beb61,Love .45,Love .45,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None,0,None,f,NaN,NaN
8,618464,c14f8d3f-ee81-416f-800f-8eff7e77a2e1,Sintellect,Sintellect,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None,0,2009-05-23 09:41:53.269195+00,f,NaN,NaN
9,285714,b68a3969-319a-462f-942b-cd35581414fc,Evie Tamala,Evie Tamala,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None,0,None,f,NaN,NaN
10,886708,2c8ae2e0-3934-440e-81f5-2ec7fd0d7899,Jean-Pierre Martin,"Martin, Jean-Pierre",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None,0,2012-04-22 19:01:53.69375+00,f,NaN,NaN
11,209107,ac63d693-7b24-4258-a3db-09743b1b4269,Deejay One,Deejay One,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None,0,None,f,NaN,NaN
12,388372,4c4b7c6f-9285-4d6a-bc10-e5c9e08045f8,wecamewithbrokenteeth,wecamewithbrokenteeth,NaN,NaN,NaN,NaN,NaN,NaN,2.0,NaN,NaN,None,0,None,f,NaN,NaN
13,726151,055f435f-dba6-4156-9050-6ac41113e45f,The Blackbelt Band,"Blackbelt Band, The",NaN,NaN,NaN,NaN,NaN,NaN,2.0,NaN,NaN,None,0,2010-06-22 04:37:31.770468+00,f,NaN,NaN
14,152659,ab1b631b-9896-4433-bef9-7868bf8a42f3,Giant Tomo,Giant Tomo,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None,0,None,f,NaN,NaN
15,3156789,da7fc031-5814-45fd-aa61-873390c6c543,OGU,OGU,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Japanese reggae singer,0,2025-12-14 23:01:35.661855+00,f,NaN,NaN
16,2064913,1fbb9556-b647-498a-a8ed-d3b5e8d7f85c,Tobias Lorsbach,"Lorsbach, Tobias",NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN,1.0,None,0,2020-10-29 11:32:33.065895+00,f,NaN,NaN
17,1000880,e6895f6e-f636-4ff6-b406-f5ddaf6cb243,Diskobitch,Diskobitch,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None,0,2013-04-25 00:05:28.234204+00,f,NaN,NaN
18,471075,4eee2c60-c2c8-4b33-b14f-0eed4bf4d11a,Seanews,Seanews,2001.0,NaN,NaN,NaN,NaN,NaN,2.0,NaN,NaN,None,0,None,f,NaN,NaN
19,98827,302d69b6-4ed9-48ec-b6dd-1c70e765b327,CyberDog,CyberDog,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None,0,None,f,NaN,NaN

=== PEEK: instrument ===

,id,gid,name,type,edits_pending,last_updated,comment,description
0,687,c1dbb66d-2356-417a-81ad-f688fee33257,guitarrón mexicano,2,0,2015-02-15 07:32:32.570132+00,None,The guitarrón mexicano is a very large and dee...
1,695,2474c241-d267-433a-a404-688b13c51d11,jouhikko,2,0,2015-02-25 19:47:04.610414+00,None,"The jouhikko is a traditional, 2 or 3 stringed..."
2,701,c0cc863c-ea65-4b8a-b365-28b81b72d846,friction idiophone,3,0,2015-02-26 10:28:49.766548+00,None,Friction idiophones are idiophones where the s...
3,706,5f9bb15a-738f-48bb-8676-55e62547726f,doshpuluur,2,0,2015-02-28 00:15:24.010482+00,None,The doshpuluur is a long-necked Tuvan lute.
4,707,9bae90ea-9729-4c30-bd3e-f8319cdf4051,igil,2,0,2015-02-28 23:39:39.01131+00,None,The igil is a Tuvan bowed string instrument wi...
5,712,c1d76a22-ab32-45af-be76-f3abd1eb2b2a,saw sam sai,2,0,2015-03-01 12:00:44.315438+00,None,The saw sam sai is a three-stringed bowed inst...
6,1003,50ae3eb1-0034-4a34-8367-aff6c30dee9a,gendèr panerus,3,0,2019-11-11 19:35:36.39114+00,Higest pitch metallophone used in Javanese gam...,"Used for simple ornamentation, it has thick sm..."
7,684,4e22ddb3-6908-4a5f-a9ae-b8a7440f6c7c,nabal,1,0,2026-02-19 21:37:08.325951+00,Korean straight brass horn,"Used in traditional music, it's long and strai..."
8,732,d3667988-a354-4fc4-9c1e-9baea9a43c06,bass oboe,1,0,2015-03-04 11:26:51.888966+00,None,The bass oboe is a double reed woodwind instru...
9,734,2ab4c035-374a-4188-bb7a-81c2558254f7,krar,2,0,2015-03-06 03:22:56.003792+00,None,The krar is a five or six-stringed bowl-shaped...
10,737,f67af2c0-3952-45e2-826a-63d140ef5c56,luthéal,2,0,2023-12-13 17:42:02.813625+00,None,The luthéal is a kind of hybrid piano which ex...
11,968,9063d25e-87e4-4adc-81d4-8fdee23bd26f,bedug,3,0,2019-05-27 15:43:02.148743+00,Very large suspended Javanese barrel drum,Extra large double-headed water buffalo hide b...
12,1013,872b72a2-541c-4115-b7ce-2dfed3e84884,bin-sitar,2,0,2020-02-27 21:07:51.082691+00,Hybrid fretted stick-zither,None
13,457,768fdb8c-494e-4dcd-9400-7345b7c3e399,Batá drum,3,0,2019-04-29 22:44:30.030288+00,Double headed hourglass Nigerian drums,Primarily in the religious rituals of the Yoru...
14,746,6dbf2716-9556-4324-9c06-a0a985cd8e78,tololoche,2,0,2015-11-04 11:32:08.756735+00,None,The tololoche is a traditional musical instrum...
15,750,034322f8-c537-4bea-acb1-d4848bd1ddc2,dolceola,2,0,2015-11-04 13:01:59.09959+00,None,A dolceola is a musical instrument resembling ...
16,752,729287b9-cc0c-4e7f-b40b-60672f6f435b,minipiano,2,0,2015-11-04 13:24:16.94016+00,None,The minipiano is a type of piano in which the ...
17,753,e1461782-0353-4f3a-a6e0-ce984f3190db,quinto,3,0,2015-11-13 11:48:59.170035+00,None,None
18,174,72ef1be2-d348-4d95-ad39-ff00a4636bd6,vertical viola,2,0,2025-09-05 12:28:11.994068+00,"Alto or vertical violin, for French ""alto"" cre...",Tuned the same as the viola but larger in size...
19,759,e2894ea4-6ac2-4c1c-98ff-2a1fac4b8f42,oktawka,2,0,2015-11-13 20:39:07.865656+00,None,Small Polish traditional fiddle.

=== PEEK: label ===

,id,gid,name,begin_date_year,begin_date_month,begin_date_day,end_date_year,end_date_month,end_date_day,label_code,type,area,comment,edits_pending,last_updated,ended
0,1,f43e252d-9ebf-4e8e-bba8-36d080756cc1,Deleted Label,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None,0,None,f
1,2,39c4dc0c-badb-4ac3-b810-e4f374dff6d9,Certificate 18,NaN,NaN,NaN,NaN,NaN,NaN,2592.0,4.0,221.0,None,0,None,f
2,103730,6f70a5cb-99a7-4a42-9208-412446d4aa0f,Flo Master Inc.,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4.0,222.0,None,0,2015-05-18 20:41:54.551166+00,f
3,29683,ccbbf728-15b8-43ee-91b6-b06967ed7f83,Xunk,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4.0,73.0,None,0,None,f
4,195899,953f5437-c702-4aaf-b7c6-d4055fe9b21b,Brother Studio Productions,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4.0,30646.0,None,0,2020-06-05 15:54:50.330605+00,f
5,16711,1e742d6b-47ea-4e53-9c64-5813b2510463,Isma'a,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4.0,73.0,None,0,None,f
6,6,5e39ea9e-3d0f-4880-8ce2-fbe561241538,Svek,1996.0,NaN,NaN,NaN,NaN,NaN,NaN,4.0,202.0,None,0,None,f
7,7768,5fb67896-f6d3-49f5-a8de-65ff17ad2dbe,Rock n' Roll Radio,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,21.0,None,0,None,f
8,294616,45b14197-41ac-4ef8-914b-31a7362b1371,senpaiこみゅ,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,107.0,doujin circle,0,2024-05-13 20:27:01.073865+00,f
9,146127,5b22cc47-5384-433b-82e3-5b5cab11a8c9,Eurobeat Union,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None,0,2017-12-10 20:06:56.906165+00,f
10,1994,34f38504-2b2c-46a8-a8c0-6246dcc5416b,Impotent Fury,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.0,221.0,None,0,None,f
11,1163,e59c5115-7ff1-42c3-8e1c-4c1c5af419d4,Kämäset levyt,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,72.0,None,0,None,f
12,267429,b9ee283e-a1ed-4514-a378-6e5fe5aae9c5,The Bureau of Lost Culture,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None,0,2023-05-15 18:27:37.444114+00,f
13,3633,f22675dc-a86b-4aca-a974-812e64764072,Fueradeserie!,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4.0,194.0,None,0,None,f
14,20105,57eb5445-e445-4dee-a643-eb32d1623b21,Idaho Music,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4.0,222.0,None,0,None,f
15,990,38f744e6-8aba-4a58-9e15-f7fff52f983b,Insekten Records,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,81.0,None,0,None,f
16,1000,1fd11a35-c054-4e48-b818-cea745bdfcba,BCMK,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.0,222.0,None,0,None,f
17,8558,e96caf8c-380e-4a9a-9d50-eb7b56366c59,Black Horizon Music,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,202.0,None,0,None,f
18,294617,7ff5c60d-e824-4bf4-b61f-919515838a9b,Leonora,NaN,NaN,NaN,NaN,NaN,NaN,NaN,9.0,NaN,None,0,2024-05-13 20:33:14.043413+00,f
19,153,a9b4f729-03b5-4eca-99cc-866ad2ab80b5,Labels UK,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,221.0,None,0,None,f

=== PEEK: genre ===

,id,gid,name,comment,edits_pending,last_updated
0,1,54c01942-22fd-4184-9877-1db0089b18f1,acid house,None,0,2019-05-13 17:46:28.122726+00
1,2,7dc2b20f-3953-4874-b9bf-41b8ba06d20c,acid jazz,None,0,2019-05-13 17:46:28.122726+00
2,3,ba64013e-27bb-4f14-a530-8d25b296e0da,acid techno,None,0,2019-05-13 17:46:28.122726+00
3,4,37f85b9c-c3fc-4b5a-8545-51aeb78c8786,acoustic blues,None,0,2019-05-13 17:46:28.122726+00
4,5,00055e8b-b951-46e2-af1e-58b5624e7952,acoustic rock,None,0,2019-05-13 17:46:28.122726+00
5,1754,a7e0229c-6e53-45f1-a6f2-a791e78b159e,afro-zouk,None,0,2022-12-21 11:47:31.756858+00
6,7,5f9cba3d-1a9f-46cd-8c49-7ed78d1f3354,alternative country,None,0,2019-05-13 17:46:28.122726+00
7,8,8301f73c-9166-4108-bfeb-4fd22dc19083,alternative dance,None,0,2019-05-13 17:46:28.122726+00
8,9,0b48a36c-630f-4ee7-8cf3-480e3dd8be65,alternative folk,None,0,2019-05-13 17:46:28.122726+00
9,10,924943cd-73c8-45c0-96eb-74f2a15e5d6e,alternative hip hop,None,0,2019-05-13 17:46:28.122726+00
10,11,7983ff25-ddf9-411e-a7f9-6cca238bff79,alternative metal,None,0,2019-05-13 17:46:28.122726+00
11,12,d3ebe947-7c03-43f5-b333-09379881b0f6,alternative pop,None,0,2019-05-13 17:46:28.122726+00
12,13,e096efc6-6c9c-4240-b627-d7bbb5e8fa2a,alternative punk,None,0,2019-05-13 17:46:28.122726+00
13,14,ceeaa283-5d7b-4202-8d1d-e25d116b2a18,alternative rock,None,0,2019-05-13 17:46:28.122726+00
14,15,608b0471-7531-4854-a348-e698c69cb699,ambient,None,0,2019-05-13 17:46:28.122726+00
15,16,cc2327cf-88a3-476b-950c-296c382eabd9,ambient house,None,0,2019-05-13 17:46:28.122726+00
16,17,1c6e4eae-915d-4662-a7ff-038920b67d9e,ambient techno,None,0,2019-05-13 17:46:28.122726+00
17,18,2c765e49-a12e-45eb-b628-f8b9cc0a0250,americana,None,0,2019-05-13 17:46:28.122726+00
18,19,e12fe025-4c13-485e-a2fe-ad5bf2cd75eb,anarcho-punk,None,0,2019-05-13 17:46:28.122726+00
19,20,aca1caab-09d1-44b5-ae84-590ff1d218fc,aor,None,0,2019-05-13 17:46:28.122726+00

=== PEEK: area ===

,id,gid,name,type,edits_pending,last_updated,begin_date_year,begin_date_month,begin_date_day,end_date_year,end_date_month,end_date_day,ended,comment
0,15449,2913ad77-cec8-4d2f-98d3-d4aa46ab73bc,Greccio,4,0,2013-07-21 22:47:57.660809+00,NaN,NaN,NaN,NaN,NaN,NaN,f,None
1,38,71bbafaa-e825-3e15-8ca9-017dcad1748b,Canada,1,0,2013-05-27 13:15:52.179105+00,NaN,NaN,NaN,NaN,NaN,NaN,f,None
2,43,82d5f4d6-aed4-3ff5-81d1-5363ac6e97a7,Chile,1,0,2013-05-27 12:52:17.320228+00,NaN,NaN,NaN,NaN,NaN,NaN,f,None
3,44,7c81bb69-a99b-3487-b6d4-0f76d7a29ca0,China,1,0,2013-05-27 12:23:26.224204+00,NaN,NaN,NaN,NaN,NaN,NaN,f,None
4,36,ee26e886-87f5-33a2-8e8e-f9591490426d,Cambodia,1,0,2013-05-27 12:26:51.100269+00,NaN,NaN,NaN,NaN,NaN,NaN,f,None
5,78,d14441fe-3bce-34b5-aed5-dfbe987329c9,Gabon,1,0,2013-05-27 12:30:24.039854+00,NaN,NaN,NaN,NaN,NaN,NaN,f,None
6,71,031eba2b-79b5-3314-a14b-288407ad42ab,Fiji,1,0,2013-05-27 12:32:56.369062+00,NaN,NaN,NaN,NaN,NaN,NaN,f,None
7,70,9ed3be5f-d54c-3add-a6a6-76c0cca54fd8,Faroe Islands,1,0,2013-05-27 12:25:34.703672+00,NaN,NaN,NaN,NaN,NaN,NaN,f,None
8,14,caac77d1-a5c8-3e6e-8e27-90b44dcc1446,Austria,1,0,2013-05-27 12:35:40.729344+00,NaN,NaN,NaN,NaN,NaN,NaN,f,None
9,63,8e0551f2-95c2-3cc0-a0a9-f2d344f10667,Egypt,1,0,2013-05-27 12:37:11.328117+00,NaN,NaN,NaN,NaN,NaN,NaN,f,None
10,42,6ce82d72-8123-3365-ab34-7b20581a34cf,Chad,1,0,2013-05-27 12:37:42.960389+00,NaN,NaN,NaN,NaN,NaN,NaN,f,None
11,18,20395c3e-610c-34fd-9995-6b6f299121f2,Bangladesh,1,0,2013-05-27 12:42:54.092754+00,NaN,NaN,NaN,NaN,NaN,NaN,f,None
12,34,5f886d01-5c12-3abb-b8be-d758b282ab05,Burkina Faso,1,0,2013-05-27 12:40:52.503929+00,NaN,NaN,NaN,NaN,NaN,NaN,f,None
13,8,aca6cbc7-4f3b-3020-8de3-c21718fe24f1,Antarctica,1,0,2013-05-27 12:41:08.497395+00,NaN,NaN,NaN,NaN,NaN,NaN,f,None
14,81,85752fda-13c4-31a3-bee5-0e5cb1f51dad,Germany,1,0,2013-05-27 12:44:37.529747+00,NaN,NaN,NaN,NaN,NaN,NaN,f,None
15,17,65f4f7a6-d3c1-3a6b-a726-85e147d555b7,Bahrain,1,0,2013-05-27 12:45:33.869648+00,NaN,NaN,NaN,NaN,NaN,NaN,f,None
16,72,6a264f94-6ff1-30b1-9a81-41f7bfabd616,Finland,1,0,2013-05-27 12:46:50.235044+00,NaN,NaN,NaN,NaN,NaN,NaN,f,None
17,67,e1c1215f-dcc0-35b4-b840-d2ca2151593b,Estonia,1,0,2013-05-27 12:48:27.302754+00,NaN,NaN,NaN,NaN,NaN,NaN,f,None
18,19,e5d8d205-81d3-3cd3-8956-d5aaa0c0173f,Barbados,1,0,2013-05-27 12:48:52.741133+00,NaN,NaN,NaN,NaN,NaN,NaN,f,None
19,76,8b681e01-6c95-3b24-ae60-5cdbcb1d7dce,French Polynesia,1,0,2013-05-27 12:51:51.903973+00,NaN,NaN,NaN,NaN,NaN,NaN,f,None

=== PEEK: tag ===

        id                                               name  ref_count
0   250930                                           italopop          1
1   246528                                          champ 700          1
2   246456                                      es war einmal          1
3   244904                                 darkness and light          1
4   246465                                          lam phaen          1
5   246541                                     hard 2 breathe          2
6   246562  penn state radio wpsu windtryst-farm cosmic-ra...          1
7   246457                                         scream-pop          1
8   285360                                     martin stray'd          5
9   181084                                       siebzehn mp3          1
10  181085                                   siebzehn torrent          1
11  181086                                           siebzehn          1
12  181087                                  siebzehn download          1
13  181088                                      siebzehn flac          1
14  253943                                 psychoactive music          1
15  246578                                    pop/rock & roll          2
16  261360                                                民族調          2
17  246543                                         to the sky          2
18    7536                                       grand rapids        249
19  248856                                         perscastle          1

=== PEEK: gender ===

   id            name
0   2          Female
1   1            Male
2   4  Not applicable
3   5      Non-binary
4   3           Other

=== PEEK: release_group ===

,id,gid,title,artist_credit,type,comment,edits_pending,last_updated
0,1964563,f59da930-70ba-4992-a346-7ed2d8e3cda8,Wande,627364,1.0,None,0,2018-04-30 23:56:50.245482+00
1,2666236,1cf5c673-171c-41fe-abfd-27a455013bbd,À nous,2966520,1.0,None,0,2021-04-22 19:12:59.273077+00
2,13,0eac6659-d590-3eb7-8c13-ed8b3fdf4ef7,The Inevitable,11,1.0,None,0,2009-05-24 20:47:00.490177+00
3,28,c554da1a-c1aa-30c3-b0bb-44b1b837de33,Piece and Love,26,1.0,None,0,2009-05-24 20:47:00.490177+00
4,60,06729175-db17-3443-add7-921739a92762,Ultimate Alternative Wavers,44,1.0,None,0,2009-05-24 20:47:00.490177+00
5,987555,e0556695-7228-4f8d-935d-b877d568211e,I’m Ready / I Don’t Know Why,1671,2.0,None,0,2019-01-05 22:42:05.1701+00
6,116,4c0130ca-24ea-38e6-acb0-7ec4c8d11945,The Glass Intact,68,1.0,None,0,2009-05-24 20:47:00.490177+00
7,144,f65dc3eb-1fa8-3d09-acf8-5366d1617ddf,Inner Booty,87,NaN,None,0,2009-05-24 20:47:00.490177+00
8,271372,5e595af2-2fdc-34a6-a692-d1657be94a28,Devil's Brothers,2147162,1.0,None,0,2018-01-18 14:00:19.866332+00
9,454,c997762b-9719-3db3-8681-4e8731324cdf,Solitude/Solitaire,327,1.0,None,0,2012-06-26 21:49:10.789859+00
10,2975367,b5f0ff5b-e166-4f6e-bf73-0827c8d2c664,6L GTR,2152096,2.0,None,0,2022-05-16 19:04:32.968256+00
11,3168729,aa3bed04-8d76-4d4e-8da6-22679df29055,Crackers (Dubblewide),3481330,1.0,None,0,2022-12-20 23:45:59.241379+00
12,2161964,65035caf-b8ab-4447-82a4-9de4b3e839d7,Hide Away / Showtime 1910,214360,2.0,None,0,2019-05-13 19:00:29.380202+00
13,422,221c72d2-5f0e-3d48-a487-f03ee609a469,Chris Isaak,313,1.0,None,0,2009-05-24 20:47:00.490177+00
14,1066615,5d70c3c7-6605-4890-96bf-f2d13b0422a1,Secret Somethings,788351,3.0,None,0,2011-05-01 07:58:12.350932+00
15,443,36881d35-b032-3705-8371-5e2bf325cc60,All the Pain Money Can Buy,320,1.0,None,0,2009-05-25 10:03:11.495821+00
16,1281,c6b36664-7e60-3b3e-a24d-d096c67a11e9,War,197,1.0,None,0,2009-05-25 22:01:30.090208+00
17,1189016,f85a11af-542c-4dc4-982c-93f79403abc2,Scared to Death,1881,2.0,None,0,2012-09-01 01:30:09.485294+00
18,1252592,d7b8575b-ec86-4faf-be06-ff838c78aee8,Emerging Field,2124154,1.0,None,0,2017-12-16 11:00:22.249493+00
19,93,78e2be48-6a07-31bf-b85f-3a1093177263,Dry,9044,1.0,None,0,2012-09-16 14:05:38.081982+00

=== PEEK: l_artist_label ===

,id,link,entity0,entity1,edits_pending,last_updated,link_order,entity0_credit,entity1_credit
0,1,12132,473113,16028,0,2011-05-16 15:03:23.368437+00,0,None,None
1,2,12132,474797,16278,0,2011-05-16 15:03:23.368437+00,0,None,None
2,3,12132,289759,16522,0,2011-05-16 15:03:23.368437+00,0,None,None
3,4,12132,2180,16962,0,2011-05-16 15:03:23.368437+00,0,None,None
4,6,12133,397208,147,0,2011-05-16 15:03:23.368437+00,0,None,None
5,52,12146,271189,357,0,2013-03-03 02:00:18.292175+00,0,None,None
6,8,12132,366366,18522,0,2011-05-16 15:03:23.368437+00,0,None,None
7,61113,12132,784809,336483,0,2025-08-29 00:40:15.139538+00,0,None,None
8,61114,12134,2933447,307087,0,2025-08-29 01:00:42.556342+00,0,None,None
9,12,12132,275019,19521,0,2011-05-16 15:03:23.368437+00,0,None,None
10,13,12132,117553,19787,0,2011-05-16 15:03:23.368437+00,0,None,None
11,14,12132,498112,20034,0,2011-05-16 15:03:23.368437+00,0,None,None
12,15,12134,476847,19165,0,2011-05-16 15:03:23.368437+00,0,None,None
13,16,12134,493566,6015,0,2011-05-16 15:03:23.368437+00,0,None,None
14,17,12134,476853,19165,0,2011-05-16 15:03:23.368437+00,0,None,None
15,18,12132,333713,16261,0,2011-05-16 15:03:23.368437+00,0,None,None
16,20,12132,163591,20851,0,2011-05-16 15:03:23.368437+00,0,None,None
17,22,12132,246509,301,0,2011-05-16 15:03:23.368437+00,0,None,None
18,23,12136,83586,677,0,2011-05-16 15:03:23.368437+00,0,None,None
19,24,12132,288546,496,0,2011-05-16 15:03:23.368437+00,0,None,None

=== PEEK: l_artist_release_group ===

,id,link,entity0,entity1,edits_pending,last_updated,link_order,entity0_credit,entity1_credit
0,1,47,162235,612285,0,2011-05-16 15:03:23.368437+00,0,None,None
1,2,101,471908,707628,0,2011-05-16 15:03:23.368437+00,0,None,None
2,4,47,469841,650261,0,2011-05-16 15:03:23.368437+00,0,None,None
3,5,101,471908,351242,0,2011-05-16 15:03:23.368437+00,0,None,None
4,9617,101,2081059,2400823,0,2020-11-28 14:19:49.946485+00,0,None,None
5,9,101,344931,185235,0,2011-05-16 15:03:23.368437+00,0,None,None
6,10,47,347,619556,0,2011-05-16 15:03:23.368437+00,0,None,None
7,12,101,527151,158078,0,2011-05-16 15:03:23.368437+00,0,None,None
8,13,47,6081,311714,0,2011-05-16 15:03:23.368437+00,0,None,None
9,15,101,468026,136212,0,2011-05-16 15:03:23.368437+00,0,None,None
10,16,101,468025,136212,0,2011-05-16 15:03:23.368437+00,0,None,None
11,18,101,471908,248035,0,2011-05-16 15:03:23.368437+00,0,None,None
12,19,282,45666,294047,0,2011-05-16 15:03:23.368437+00,0,None,None
13,21,47,56941,749536,0,2011-05-16 15:03:23.368437+00,0,None,None
14,22,47,56941,760787,0,2011-05-16 15:03:23.368437+00,0,None,None
15,23,47,336087,800019,0,2011-05-16 15:03:23.368437+00,0,None,None
16,25,47,191,728898,0,2011-05-16 15:03:23.368437+00,0,None,None
17,26,47,10042,706338,0,2011-05-16 15:03:23.368437+00,0,None,None
18,13941,254715,1921879,1491710,0,2024-01-20 20:20:32.07656+00,0,None,None
19,28,47,246062,518671,0,2011-05-16 15:03:23.368437+00,0,None,None

=== PEEK: label_tag ===

     label     tag  count                   last_updated
0   241710     235      1  2022-05-17 09:34:03.579706+00
1   171313       7      1  2022-12-21 12:49:53.319143+00
2   256852     303      1  2022-12-21 16:32:07.702476+00
3    28383      20      1  2026-03-02 13:56:53.809873+00
4   353952      58      1  2026-03-02 20:10:28.493383+00
5   353962      77      1  2026-03-02 22:19:40.775017+00
6   353955     537      1  2026-03-02 22:50:49.640072+00
7   173965    1519      1  2022-05-18 00:20:03.219785+00
8    81687      26      1  2022-05-18 08:21:10.655119+00
9    81687   41079      1  2022-05-18 08:21:10.707491+00
10  241776      19      1   2022-05-18 10:06:46.14728+00
11  286641     235      1  2024-01-21 14:17:33.239955+00
12  220679   23623      1  2022-12-21 20:49:34.598998+00
13  240487      75      1  2022-05-19 12:03:16.295598+00
14  241808  242136      1  2022-05-20 13:42:26.945676+00
15  257229   70033      1  2022-12-22 11:45:43.342025+00
16  286648     235      1  2024-01-21 15:45:05.047645+00
17  123533  255925      1  2024-01-21 16:08:47.869616+00
18  207391      26      1  2022-05-22 07:37:59.253589+00
19  207391      27      1  2022-05-22 07:37:59.273874+00

=== PEEK: l_artist_genre ===

,id,link,entity0,entity1,edits_pending,last_updated,link_order,entity0_credit,entity1_credit
0,1,1117609,34423,94,0,2024-07-22 10:30:16.505638+00,0,None,None
1,81,1117609,3221251,86,0,2026-03-18 18:04:42.678456+00,0,None,None
2,82,1117609,435717,15,0,2026-04-15 15:15:20.632253+00,0,None,None
3,83,1117609,435717,145,0,2026-04-15 15:15:20.632253+00,0,None,None
4,84,1117609,435717,204,0,2026-04-15 15:15:20.632253+00,0,None,None
5,85,1117609,435717,233,0,2026-04-15 15:15:20.632253+00,0,None,None

=== PEEK: l_artist_artist ===

        id  link  entity0  entity1
0        1  6337   475809   287770
1        3  6338   238828     3184
2        6  6337   367163   493186
3        7  6340   510355   510353
4        9  6342   446404     3184
5   178950  6337   636373   805194
6   831332  6337  2985343   648000
7       14  6340   515380   512604
8       17  6337   537292   537094
9       18  6337   542336   221122
10  649342  6340  1816108  1303285
11  185753  6340   285421   839935
12      22  6340   567288   567286
13  377869  6380   918876   145951
14  179135  6380   805591   739697
15  538724  6358  1149172    74234
16      26  6337    57463    57467
17  735574  6337  2679113  2679123
18  117994  6337   130768   180604
19      30  6337   571201   571196

=== PEEK: release_group_tag ===

    release_group     tag  count                   last_updated
0         1835483    1409      1  2023-05-15 18:32:20.755277+00
1          445144      11      1  2022-05-16 18:34:51.007922+00
2         3413902     564      1  2023-08-28 20:17:36.074492+00
3         1010254   32086      1  2022-12-21 00:23:20.655683+00
4          445144      20      1  2022-05-16 18:34:51.206616+00
5         3168744   32086      1  2022-12-21 00:34:02.991273+00
6          445321     166      1  2022-05-16 18:34:51.655111+00
7          445144       7      1  2022-05-16 18:34:51.980537+00
8          818910      19      1  2022-05-18 02:36:10.069792+00
9           36712       7      1  2022-05-19 18:00:52.225965+00
10         572463       7      1  2022-05-19 18:00:52.240402+00
11        3117108    1409      1  2023-05-15 18:32:39.454648+00
12         572954    1028      1  2022-05-19 18:00:52.631774+00
13         572956    1028      1  2022-05-19 18:00:52.648884+00
14         572951    1028      1  2022-05-19 18:00:52.694989+00
15        3168398     343      1  2022-12-21 01:46:46.676204+00
16        3168797   29739      1  2022-12-21 05:16:41.802934+00
17        2867122     517      1  2022-08-06 09:21:17.631845+00
18         707777      20      1  2022-05-23 06:41:32.042641+00
19        2813123  255139      1  2026-03-27 08:50:25.358734+00

=== PEEK: artist_tag ===

     artist     tag  count                   last_updated
0   2447565     523      1  2022-12-20 23:53:49.511627+00
1   2337807     204      1  2022-05-16 20:32:27.098355+00
2   2734633      55      1  2025-04-21 06:50:37.457808+00
3   3146785     235      1  2025-12-05 19:58:20.271273+00
4    441774     186      1  2022-05-17 00:44:28.423397+00
5    226055    1078      1  2024-05-13 20:22:51.195287+00
6     57186  117593     -1  2022-05-17 02:07:51.200395+00
7    512057     786      1  2022-05-17 02:38:12.460518+00
8   1498963      11      1  2022-05-17 07:01:15.746156+00
9   2337614   34236      1  2022-05-17 07:53:50.749109+00
10  2337614    5853      1  2022-05-17 07:53:50.905677+00
11  1035805     483      1  2022-05-17 09:02:56.343278+00
12   262731    1047      1  2026-03-20 23:12:36.017076+00
13  2334582      11      1  2022-05-17 13:37:20.004788+00
14    23185   51492      0  2022-05-17 14:59:49.622809+00
15   678983    1156      1  2024-10-17 18:31:49.688209+00
16  1462933   22212      1  2022-05-17 17:20:58.780508+00
17   913333  133705      1   2022-05-17 17:23:35.94051+00
18   913333     147      1  2022-05-17 17:23:35.953927+00
19  2189305     235      0  2022-05-17 20:16:08.978792+00

=== PEEK: artist_credit ===

,id,name,artist_count,ref_count,created,edits_pending,gid
0,4229350,"Jean-Paul Fouchécourt, Yvonne Naef, Saito Kine...",4,1,2024-12-20 06:18:14.699053+00,0,25966362-45fb-4457-88c7-b0d9b06f28e6
1,3320885,The Turns,1,1,2022-06-09 14:46:02.184524+00,0,490c3930-5600-4796-9da6-b05be0a42f66
2,3320887,Son.Sine,1,1,2022-06-09 14:46:02.184524+00,0,9d4b38cf-78f5-4d83-b561-353bec3f9856
3,3431907,Auggië,1,4,2022-10-22 20:20:54.455395+00,0,eb842839-9ca9-4444-a212-52f1a97d3203
4,3435757,Joe Innes & the Cavalcade,1,5,2022-10-27 04:00:23.539507+00,0,3dcd9d03-9f39-4f7e-ba6a-b58adf7df552
5,2046854,"Faith Esham, Orchestre national de France, Lor...",3,4,2017-08-06 02:19:33.246689+00,0,f6e5728b-2b9e-36f8-b271-cec2790117d0
6,4229351,"Yvonne Naef, Jean-Paul Fouchécourt, Saito Kine...",4,1,2024-12-20 06:18:14.699053+00,0,11ac772a-6760-4f67-8cdb-b6be74df6536
7,3431909,EdOne & Knoder,2,2,2022-10-22 20:20:54.455395+00,0,493fa7b7-077f-45f8-85b9-e2395b42fe64
8,629280,Gregorio Paniagua,1,110,2011-05-16 16:32:11.963929+00,0,5e794497-9afb-3899-89a0-7732994fbe69
9,3388535,"Dayna Stephens, Andre Sumelius, George Kontraf...",4,18,2022-08-31 06:19:14.617717+00,0,9308906a-46dd-4c6d-bfda-9c0d56faf1e4
10,3392212,"Jacques Jouineau, Chœur de Radio France, Susan...",10,1,2022-09-04 19:58:23.198515+00,0,785a560d-b969-4c26-a335-4918c9a5f075
11,4229352,"Anna Christy, Isabel Leonard, Saito Kinen Orch...",4,1,2024-12-20 06:18:14.699053+00,0,bfcd1a11-a719-44fc-95e3-e4925baf8dfa
12,3431911,Liebig,1,2,2022-10-22 20:20:54.455395+00,0,1afcebe4-84bc-47be-ae04-8efe7120f460
13,3671937,Orff; Rafael Frühbeck de Burgos,2,1,2023-07-18 05:16:36.842429+00,0,ee04364e-dde7-4a0b-bb2a-5e4d66bff31b
14,3384120,Jimmy Blythe & Charles Clark,2,1,2022-08-26 03:00:24.480089+00,0,4e3c97a5-832a-4beb-995b-f84387038ddf
15,213907,La Flavour,1,71,2011-05-16 16:32:11.963929+00,0,bef9a74a-18d7-30f5-871c-17e3a20db2c0
16,3392217,"Plácido Domingo, Ruggero Raimondi, Orchestre n...",4,2,2022-09-04 19:58:37.352339+00,0,be6f5a66-8882-4373-8185-f0a58f2cc9aa
17,3325471,moxwav,1,1,2022-06-15 03:43:03.999361+00,0,d78e5db2-7731-4792-935c-020733d438fa
18,2487235,Ansonix,1,33,2019-08-27 20:32:41.36261+00,0,735e6b21-5e31-3746-8428-f3f673034e4b
19,3031381,MatthewJ217,1,5,2021-06-20 11:58:21.912491+00,0,2f791196-b285-3ea5-859f-2ecd60838b16

=== PEEK: artist_credit_name ===

    artist_credit  position   artist                    name join_phrase
0          578352         0   578352           Gustav Ruppke        None
1          273232         0   273232                 Zachary        None
2          153193         0   153193  The High Level Ranters        None
3           32262         0    32262        Georges Brassens        None
4         1389968         0  1171184    Harvard of the South        None
5          145773         0   145773            Aric Leavitt        None
6         1258383         0  1075202          Delfino Square        None
7         2125299         0    21361                  Bartók          ,
8          220155         0   220155                Love .45        None
9         2402197         0   847590               Protostar      feat.
10         140751         0   140751                 Sprites        None
11         578364         0   578364                  Machin        None
12         618464         0   618464              Sintellect        None
13         285714         0   285714             Evie Tamala        None
14         413616         0   413616         Wieland Samolak        None
15        1156350         0   997907             John Nauman        None
16         209107         0   209107              Deejay One        None
17         388372         0   388372   wecamewithbrokenteeth        None
18         726151         0   726151      The Blackbelt Band        None
19          99188         0    99188         Toni Holgersson        None

=== PEEK: l_artist_instrument ===

,id,link,entity0,entity1,edits_pending,last_updated,link_order,entity0_credit,entity1_credit
0,1,311992,1218252,121,0,2016-08-01 11:22:19.207793+00,0,None,None
1,2,312066,1395197,19,0,2016-08-01 14:14:07.499778+00,0,None,None
2,24,393478,1261488,808,0,2017-05-31 08:31:04.355584+00,0,None,None
3,4,312066,1395235,118,0,2016-08-01 18:16:51.429318+00,0,None,None
4,5,312066,1395197,21,0,2016-08-01 18:18:38.812703+00,0,None,None
5,6,312066,173057,779,0,2016-08-01 18:21:47.746656+00,0,None,None
6,7,312066,1395236,737,0,2016-08-01 18:21:59.822953+00,0,None,None
7,8,312066,1395237,139,0,2016-08-01 18:24:33.983833+00,0,None,None
8,9,312096,1395244,778,0,2016-08-01 18:33:50.830055+00,0,None,None
9,62,451269,1595656,890,0,2017-12-12 21:15:53.856419+00,0,None,None
10,11,312066,1395262,780,0,2016-08-02 14:35:27.803949+00,0,None,None
11,63,452102,1596965,894,0,2017-12-16 04:16:23.489723+00,0,None,None
12,13,312066,1396465,260,0,2016-08-06 16:52:58.728402+00,0,None,None
13,14,312066,1396508,780,0,2016-08-06 20:19:21.198133+00,0,None,None
14,64,452104,124402,183,0,2017-12-16 04:23:35.126864+00,0,None,None
15,403,312066,580555,278,0,2024-11-08 23:09:49.668593+00,0,None,None
16,21,312066,1396778,799,0,2016-08-24 09:32:05.541821+00,0,Bartolomeo Cristofori,None
17,22,312066,1127022,804,0,2016-10-14 08:08:04.482633+00,0,None,None
18,65,312066,1600693,89,0,2017-12-24 20:31:41.04257+00,0,None,None
19,66,312066,1600695,89,0,2017-12-24 20:34:39.278295+00,0,None,None

=== PEEK: link ===

,id,link_type,begin_date_year,begin_date_month,begin_date_day,end_date_year,end_date_month,end_date_day,attribute_count,created,ended
0,48067,148,NaN,NaN,NaN,NaN,NaN,NaN,2,2012-05-15 20:52:02.141676+00,f
1,2,6,NaN,NaN,NaN,NaN,NaN,NaN,0,2011-05-16 15:03:23.368437+00,f
2,3,2,NaN,NaN,NaN,NaN,NaN,NaN,0,2011-05-16 15:03:23.368437+00,f
3,4,2,NaN,NaN,NaN,NaN,NaN,NaN,1,2011-05-16 15:03:23.368437+00,f
4,5,1,NaN,NaN,NaN,NaN,NaN,NaN,0,2011-05-16 15:03:23.368437+00,f
5,6,1,NaN,NaN,NaN,NaN,NaN,NaN,1,2011-05-16 15:03:23.368437+00,f
6,30853,103,2011.0,10.0,NaN,NaN,NaN,NaN,0,2011-10-30 18:54:18.334591+00,f
7,8,9,NaN,NaN,NaN,NaN,NaN,NaN,0,2011-05-16 15:03:23.368437+00,f
8,9,15,NaN,NaN,NaN,NaN,NaN,NaN,0,2011-05-16 15:03:23.368437+00,f
9,10,17,NaN,NaN,NaN,NaN,NaN,NaN,0,2011-05-16 15:03:23.368437+00,f
10,12,8,NaN,NaN,NaN,NaN,NaN,NaN,0,2011-05-16 15:03:23.368437+00,f
11,48069,278,2003.0,4.0,19.0,2003.0,4.0,19.0,2,2012-05-15 23:09:11.460041+00,t
12,14,10,NaN,NaN,NaN,NaN,NaN,NaN,0,2011-05-16 15:03:23.368437+00,f
13,145207,278,2012.0,4.0,16.0,2012.0,4.0,16.0,1,2014-01-06 21:18:50.297735+00,t
14,167219,743,NaN,NaN,NaN,NaN,NaN,NaN,1,2014-05-14 18:06:30.248383+00,f
15,103598,150,1990.0,5.0,7.0,1990.0,5.0,12.0,0,2013-01-03 12:48:49.39038+00,t
16,124603,148,2006.0,1.0,12.0,2006.0,1.0,15.0,2,2013-07-15 10:51:22.091207+00,t
17,60199,151,2004.0,1.0,NaN,2004.0,1.0,NaN,0,2012-10-06 00:00:10.028137+00,t
18,20,15,NaN,NaN,NaN,NaN,NaN,NaN,1,2011-05-16 15:03:23.368437+00,f
19,241864,268,2007.0,NaN,NaN,NaN,NaN,NaN,0,2015-05-18 19:04:59.502166+00,f

=== PEEK: link_type ===

,id,parent,child_order,gid,entity_type0,entity_type1,name,description,link_phrase,reverse_link_phrase,long_link_phrase,last_updated,is_deprecated,has_dates,attribute_count,priority
0,12,NaN,0,38278b3b-30e6-304c-b0db-5ba701eb0268,release_group,release_group,covers and versions,None,covers or other versions,covers or other versions,covers and versions,2014-05-18 09:46:23.72719+00,f,f,0,0
1,735,NaN,0,12678b88-1adb-3536-890e-9b39b9a14b2d,instrument,instrument,children,None,children,child of,has child,2014-05-18 10:41:05.403719+00,f,f,0,0
2,870,784.0,0,4789521b-57b9-4689-9644-46de63190f66,series,url,soundcloud,"This links a series (most commonly, but not ne...",SoundCloud,SoundCloud page for,has a SoundCloud page at,2015-12-16 11:53:10.160133+00,f,t,0,0
3,957,NaN,2,a6874915-b6a3-42ef-82af-6ba800d1e940,label,url,get the music,None,get the music,get the music,get the music,2018-05-18 10:37:46.114037+00,f,f,0,0
4,227,234.0,0,451076df-61cf-46ab-9921-555cab2f050d,recording,recording,DJ-mix,"This is used to link a <a href=""/doc/Mix_Termi...",DJ-mix of,DJ-mixes,is a DJ-mix of,2021-02-02 10:14:29.683106+00,f,t,0,0
5,754,188.0,0,8147b6a2-ad14-4ce7-8f0a-697f9a31f68f,artist,url,IMSLP,"This links an artist to its page in <a href=""h...",IMSLP,IMSLP page for,has an IMSLP page at,2020-02-17 13:17:20.780295+00,f,t,0,0
6,921,NaN,1,9900c8c5-9844-4f10-8403-23aabafd913c,url,work,work list entry,This link points to a page for a particular wo...,work list entry for,work list entry,{entity1} has a work list entry at {entity0},2019-08-14 15:57:32.555087+00,f,t,0,0
7,2,4.0,0,fc399d47-23a7-4c28-bfcf-0607a562b644,release,release,transl-tracklisting,This indicates that one release is identical t...,transliterated/translated track listings,transliterated/translated track listing of,is the original for the transliterated/transla...,2015-07-17 08:53:57.281375+00,f,f,0,0
8,154,157.0,1,83f72956-2007-4bca-8a97-0ae539cca99d,artist,recording,samples from artist,Indicates that the recording contains samples ...,produced material that was {additional:additio...,contains {additional} samples by,{entity1} contains {additional} samples by {en...,2015-11-05 16:48:09.775478+00,f,t,1,0
9,871,54.0,3,4db37fec-eb67-45d3-b4fa-148a68135fbb,artist,release,translator,Indicates the person who translated the lyrics...,translated,{additional} translator,{additional:additionally} translated,2015-08-18 22:41:18.220935+00,f,t,1,0
10,1229,12.0,2,26ce3301-cf1f-4ce4-a7e2-9670f9a9e1d5,release_group,release_group,re‐recording,This relationship type is used to indicate tha...,re‐recording of,re‐recordings,is a re‐recording of,2025-06-08 09:59:15.264427+00,f,f,0,0
11,873,NaN,1,e02f372b-33c3-41fc-88ba-6b3e95f50d77,area,work,written in,This links a work with the area it was written...,{additional} writing location for,{additional:additionally} written in,{entity1} was {additional:additionally} writte...,2015-11-05 16:11:57.167503+00,f,t,1,0
12,937,1164.0,0,7f7d829b-6ba8-4f86-be90-c9372ef9a679,artist,place,composer-in-residence,This links a place (often a concert hall or ed...,composer-in-residence at,composers-in-residence,was a composer-in-residence at,2023-06-12 09:53:51.942995+00,f,t,0,0
13,745,NaN,0,b79eb9a5-46df-492d-b107-1f1fea71b0eb,series,url,official homepage,Indicates the official homepage for a series.,official homepages,official homepage for,has an official homepage at,2015-12-16 11:48:26.565524+00,f,t,0,0
14,1088,NaN,0,25ed73f8-a864-42cf-8b9c-68db198dbe0e,area,genre,genre origin,This relationship type links genres to the are...,genres,from,{entity1} is a genre from {entity0},2022-07-07 10:09:30.156015+00,f,f,0,0
15,256,NaN,0,c0b9cc44-ea3b-4312-94f9-577c2605d305,recording,url,production,None,production,production,production,2014-05-18 09:46:35.566998+00,f,f,0,0
16,969,42.0,0,904e57f3-cbbc-43ab-8798-13e710e400d3,artist,release,lacquer cut,Links a release to the engineer who did the la...,lacquer cut,lacquer cut,cut the lacquer for,2018-08-25 10:07:01.469827+00,f,t,1,0
17,755,82.0,0,90ff18ad-3e9d-4472-a3d1-71d4df7e8484,release,url,allmusic,This is used to link a release to its correspo...,Allmusic,Allmusic page for,has an Allmusic page at,2019-08-14 16:09:07.914092+00,f,t,0,0
18,925,NaN,4,72854c7e-ebf8-4b73-9b2c-ee08e83b9480,artist,place,educational institution connection,None,educational institution connection,connected with,is connected to the educational institution,2018-01-28 08:55:14.430577+00,f,f,0,0
19,56,54.0,1,a2af367a-b040-46f8-af21-310f92dfe97b,artist,release,lyricist,Indicates the lyricist for this release.,{additional} lyrics,{additional} lyricist,{additional:additionally} wrote the lyrics for,2020-04-25 09:33:34.877117+00,f,t,1,0

# FOREIGN KEY MAP (for navigating the database)

In [10]:
foreign_key_map = {
    "artist": {
        "type":       ("artist_type", "id"),
        "area":       ("area", "id"),
        "gender":     ("gender", "id"),
        "begin_area": ("area", "id"),
        "end_area":   ("area", "id"),
    },
    "instrument": {
        "type": ("instrument_type", "id"),
    },
    "label": {
        "type": ("label_type", "id"),
        "area": ("area", "id"),
    },
    "release_group": {
        "type":          ("release_group_primary_type", "id"),
        "artist_credit": ("artist_credit", "id"),
    },
    "artist_credit_name": {
        "artist_credit": ("artist_credit", "id"),
        "artist":        ("artist", "id"),
    },
    "label_tag": {
        "label": ("label", "id"),
        "tag":   ("tag", "id"),
    },
    "artist_tag": {
        "artist": ("artist", "id"),
        "tag":    ("tag", "id"),
    },
    "release_group_tag": {
        "release_group": ("release_group", "id"),
        "tag":           ("tag", "id"),
    },
    "l_artist_genre": {
        "link":    ("link", "id"),
        "entity0": ("artist", "id"),
        "entity1": ("genre", "id"),
    },
    "l_release_group_genre": { 
        "link":    ("link", "id"),
        "entity0": ("release_group", "id"),
        "entity1": ("genre", "id"),
    },
    "l_artist_label": {
        "link":    ("link", "id"),
        "entity0": ("artist", "id"),
        "entity1": ("label", "id"),
    },
    "l_artist_release_group": {
        "link":    ("link", "id"),
        "entity0": ("artist", "id"),
        "entity1": ("release_group", "id"),
    },
    "l_artist_artist": {
        "link":    ("link", "id"),
        "entity0": ("artist", "id"),
        "entity1": ("artist", "id"),
    },
    "l_artist_instrument": {
        "link":    ("link", "id"),
        "entity0": ("artist", "id"),
        "entity1": ("instrument", "id"),
    },
    "link": {
        "link_type": ("link_type", "id"),
    },
    "link_type": {
        "parent": ("link_type", "id"),
    },
}

Great work on the map! I just removed "artist_genre" and "release_group_genre" because I couldn't find those tables in the database. But I'm pretty sure it's correct

# TESTING SOME BASIC SQL QUERIES

Here are some cool queries

In [11]:
for table_name, df in dfs.items():
    df.createOrReplaceTempView(table_name)

In [12]:
def peek(df, n=20):
    return display(df.limit(n).toPandas())

***

1) Select all from artist

In [13]:
peek(spark.sql("""
    SELECT *
    FROM artist
"""))

,id,gid,name,sort_name,begin_date_year,begin_date_month,begin_date_day,end_date_year,end_date_month,end_date_day,type,area,gender,comment,edits_pending,last_updated,ended,begin_area,end_area
0,2252039,fadeb38c-833f-40bc-9d8c-a6383b38b1be,Доктор Сатана,Доктор Сатана,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None,0,2021-11-23 07:08:52.479537+00,f,NaN,NaN
1,371203,49add228-eac5-4de8-836c-d75cde7369c3,Pete Moutso,"Moutso, Pete",NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN,NaN,None,0,None,f,NaN,NaN
2,3087346,dfdce491-133d-4e9f-9e48-795587e181b0,UNlT,UNlT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None,0,2025-09-14 23:53:28.004798+00,f,NaN,NaN
3,2851271,165a49a0-2b3b-4078-a3c1-905afdc07c0a,Babyglock,Babyglock,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None,0,2024-10-19 03:33:55.474151+00,f,NaN,NaN
4,145773,7b4a548e-a01a-49b7-82e7-b49efeb9732c,Aric Leavitt,"Leavitt, Aric",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None,0,None,f,NaN,NaN
5,1076328,60aca66f-e91a-4cb5-9308-b6e293cd833e,Fonograff,Fonograff,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None,0,2014-01-10 16:25:20.992213+00,f,NaN,NaN
6,1172876,3e1bd546-d2a7-49cb-b38d-d70904a1d719,Al Street,"Street, Al",NaN,NaN,NaN,NaN,NaN,NaN,1.0,222.0,1.0,None,0,2014-11-23 14:07:19.782509+00,f,NaN,NaN
7,220155,df120895-f6c6-4a66-b9cf-73350f0beb61,Love .45,Love .45,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None,0,None,f,NaN,NaN
8,618464,c14f8d3f-ee81-416f-800f-8eff7e77a2e1,Sintellect,Sintellect,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None,0,2009-05-23 09:41:53.269195+00,f,NaN,NaN
9,285714,b68a3969-319a-462f-942b-cd35581414fc,Evie Tamala,Evie Tamala,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None,0,None,f,NaN,NaN
10,886708,2c8ae2e0-3934-440e-81f5-2ec7fd0d7899,Jean-Pierre Martin,"Martin, Jean-Pierre",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None,0,2012-04-22 19:01:53.69375+00,f,NaN,NaN
11,209107,ac63d693-7b24-4258-a3db-09743b1b4269,Deejay One,Deejay One,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None,0,None,f,NaN,NaN
12,388372,4c4b7c6f-9285-4d6a-bc10-e5c9e08045f8,wecamewithbrokenteeth,wecamewithbrokenteeth,NaN,NaN,NaN,NaN,NaN,NaN,2.0,NaN,NaN,None,0,None,f,NaN,NaN
13,726151,055f435f-dba6-4156-9050-6ac41113e45f,The Blackbelt Band,"Blackbelt Band, The",NaN,NaN,NaN,NaN,NaN,NaN,2.0,NaN,NaN,None,0,2010-06-22 04:37:31.770468+00,f,NaN,NaN
14,152659,ab1b631b-9896-4433-bef9-7868bf8a42f3,Giant Tomo,Giant Tomo,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None,0,None,f,NaN,NaN
15,3156789,da7fc031-5814-45fd-aa61-873390c6c543,OGU,OGU,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Japanese reggae singer,0,2025-12-14 23:01:35.661855+00,f,NaN,NaN
16,2064913,1fbb9556-b647-498a-a8ed-d3b5e8d7f85c,Tobias Lorsbach,"Lorsbach, Tobias",NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN,1.0,None,0,2020-10-29 11:32:33.065895+00,f,NaN,NaN
17,1000880,e6895f6e-f636-4ff6-b406-f5ddaf6cb243,Diskobitch,Diskobitch,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None,0,2013-04-25 00:05:28.234204+00,f,NaN,NaN
18,471075,4eee2c60-c2c8-4b33-b14f-0eed4bf4d11a,Seanews,Seanews,2001.0,NaN,NaN,NaN,NaN,NaN,2.0,NaN,NaN,None,0,None,f,NaN,NaN
19,98827,302d69b6-4ed9-48ec-b6dd-1c70e765b327,CyberDog,CyberDog,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None,0,None,f,NaN,NaN

***

2. Select all artists and their labels

In [14]:
peek(spark.sql("""
    SELECT a.name AS artist_name, l.name AS label
    FROM l_artist_label lal
    JOIN artist a ON lal.entity0 = a.id
    JOIN label l ON lal.entity1 = l.id
"""))

            artist_name                              label
0                s'Poom                Legendaarne Records
1            Guido Elmi                              Nopop
2         Marco Resmann                           Upon.You
3   Karl-Jonas Winqvist                Sing a Song Fighter
4          Stuart Brown             British Film Institute
5            Earl Young  Baker, Harris & Young Productions
6          Alexia Coley                   Jalapeno Records
7         Darren Hickey                          Xpressive
8         Darren Hickey                      Juice Records
9          Ras Sheehama                African Cream Music
10     Guadalupe Pineda                         InterSound
11       Gavin Hardkiss                           Hardkiss
12               Whitey                             Spoilt
13               Whitey                          NO! Label
14               Escala                         Syco Music
15      Robbie Hardkiss                           Hardkiss
16          Christafari                      Gotee Records
17         Samsun Demir                Doğan Music Company
18       Fred Henderson        Henderson Music Productions
19        The Svengalis                Villains and Rogues

***

3. Number of release groups per artist sorted by most prolific

In [15]:
peek(spark.sql("""
    SELECT a.name AS artist_name, COUNT(rg.id) AS release_group_count
    FROM release_group rg
    JOIN artist_credit_name acn ON rg.artist_credit = acn.artist_credit
    JOIN artist a ON acn.artist = a.id
    GROUP BY a.name
    ORDER BY release_group_count DESC
"""))

                  artist_name  release_group_count
0             Various Artists               281842
1        Ludwig van Beethoven                 6088
2       Johann Sebastian Bach                 6011
3     Wolfgang Amadeus Mozart                 5922
4                   [unknown]                 3432
5             Johannes Brahms                 2946
6              Franz Schubert                 2852
7       Пётр Ильич Чайковский                 2684
8             Antonio Vivaldi                 2143
9           Bruce Springsteen                 2127
10            Fryderyk Chopin                 2008
11  London Symphony Orchestra                 1963
12               Joseph Haydn                 1959
13            Robert Schumann                 1959
14                  Zippy Kid                 1941
15           Armin van Buuren                 1938
16         The Rolling Stones                 1897
17     George Frideric Handel                 1740
18             Antonín Dvořák                 1676
19             user-177606669                 1654

***

4. Number of labels per country

In [16]:
peek(spark.sql("""
    SELECT a.name as area, COUNT(l.id) as label_count
    FROM label l
    JOIN area a ON l.area = a.id
    GROUP BY a.name
    ORDER BY label_count DESC
    LIMIT 20
"""))

              area  label_count
0    United States        30680
1   United Kingdom        14758
2            Japan        12059
3          Germany         9388
4           France         5974
5            Italy         4110
6           Canada         3227
7           Sweden         2933
8      Netherlands         2893
9            Spain         2345
10          London         2341
11       Australia         2231
12          Russia         1868
13         Finland         1843
14        New York         1704
15         Belgium         1656
16     South Korea         1629
17          Berlin         1320
18          Brazil         1317
19          Norway         1269

***

5. Number of artists by gender

In [17]:
peek(spark.sql("""
    SELECT g.name AS gender, COUNT(*) AS count
    FROM artist a
    JOIN gender g ON a.gender = g.id
    GROUP BY g.name
    ORDER BY count DESC
"""))

           gender   count
0            Male  932192
1          Female  280203
2  Not applicable    2443
3      Non-binary    2237
4           Other    1787

***

6. Relationships between artists and their labels

In [18]:
peek(spark.sql("""
    SELECT 
    a.name as artist,
    l.name as label,
    lt.name as relationship_type,
    lnk.begin_date_year,
    lnk.end_date_year
    FROM l_artist_label lal
    JOIN artist a ON lal.entity0 = a.id
    JOIN label l ON lal.entity1 = l.id
    JOIN link lnk ON lal.link = lnk.id
    JOIN link_type lt ON lnk.link_type = lt.id
"""))

,artist,label,relationship_type,begin_date_year,end_date_year
0,Murdock,Radar Records,label founder,2010,NaN
1,Empty Pools,Battle Worldwide Recordings,recording contract,2011,NaN
2,Dr. Jekyll,Hirntot Records,recording contract,2006,2011.0
3,eXiled,Foundry Music,recording contract,2013,NaN
4,Ben Kass,Underground Music,creative position at,2009,NaN
5,Iron Mike Norton,GFO Records,producer position at,2007,NaN
6,Social Distortion,Restless Records,recording contract,1988,1989.0
7,Excel,Caroline Records,recording contract,1988,1989.0
8,Henry Burr,Henry Burr Music Corp.,label founder,1919,1919.0
9,Dan Miracle,Reinforced Records,producer position at,2003,2004.0
10,Mike Kukin,Headway Music,recording contract,2010,2011.0
11,Bernhard Christoph Breitkopf,Breitkopf & Härtel,label founder,1719,1719.0
12,Nikki Forova,37 Records,recording contract,2010,2013.0
13,Brasco,Bombattak Recordz,recording contract,2005,2010.0
14,Bishop Lamont,Aftermath Entertainment,recording contract,2005,2010.0
15,Barnali Kalita,Margherita and Associate,recording contract,2005,2010.0
16,Najoua Belyzel,Scorpio Music,recording contract,2005,2010.0
17,김규종,DSP Media,recording contract,2005,2010.0
18,SS501,DSP Media,recording contract,2005,2010.0
19,Crash Romeo,Trustkill Records,recording contract,2005,2010.0

***

7. Possible types of relationships that can exist between an artist and a label

In [19]:
peek(spark.sql("""
    SELECT id, name, link_phrase
    FROM link_type
    WHERE entity_type0 = 'artist' AND entity_type1 = 'label'
"""))

      id                                name                      link_phrase
0   1258                  named after artist       inspired the name of label
1    119                         position at                      employed by
2   1259                   named after label                named after label
3    724                  personal publisher           has personal publisher
4    115                creative position at                creative position
5    990                           ownership                        ownership
6    116                       label founder                          founded
7    120                engineer position at                engineer position
8   1081  artists and repertoire position at  artists and repertoire position
9    723                      personal label               has personal label
10   991                               owner                             owns
11   121                  recording contract                        signed by
12   117                producer position at                producer position
13  1266               executive position at               executive position

***

Some sanity checking procedures...

In [22]:
peek(spark.sql("""
    SELECT COUNT(*) as matched
    FROM l_artist_label lal
    JOIN artist a ON lal.entity0 = a.id
    JOIN label l ON lal.entity1 = l.id
"""))

peek(spark.sql("""
    SELECT COUNT(*) FROM l_artist_label
"""))

   matched
0    64053

   count(1)
0     64053

In [26]:
peek(spark.sql("""
    SELECT COUNT(*) as matched
    FROM artist_tag at
    JOIN tag t ON at.tag = t.id
"""))

peek(spark.sql("""
    SELECT COUNT(*) as total FROM artist_tag
"""))

   matched
0   724177

    total
0  724177

Nulls analysis

In [24]:
peek(spark.sql("""
    SELECT
        SUM(CASE WHEN type IS NULL THEN 1 ELSE 0 END) as null_type,
        SUM(CASE WHEN area IS NULL THEN 1 ELSE 0 END) as null_area,
        SUM(CASE WHEN gender IS NULL THEN 1 ELSE 0 END) as null_gender,
        COUNT(*) as total
    FROM artist
"""))

   null_type  null_area  null_gender    total
0     638626    1438400      1634292  2853154

***

# Part 2, #5: Preprocessing Plan

Our first milestone will be to build a K-Nearest Neighbors which groups music based on its "DNA" (instruments, genres, labels, etc), so the first step will be to determine precisely which variables constitute part of music's DNA, and determining their relative importance. The next step will be to strip away unnecessary information, such as columns and tables we won't need (for example: "description" in the instruments table, since it contains natural language, will not be helpful for this problem). 

The data has a high volume of nulls. Depending on the data type these will need to be dealt with differently - for example, date columns might be left as nulls because imputing an "average" date probably doesn't make any sense. "Type" columns (which indicate something else for each table, but can refer to things like release type: original, bootleg, reissue, etc) have their most common entry set to 1, so nulls in that variable will likely be set to 1. There are also lots of entries in which most data is null - since the dataset is so large, some sets of rows might be filtered out completely.

We will primarily use SQL for preparing the data that we will operate on, then switch over to Python for filling nulls and cleaning. Some Spark transformations we may use include join, groupBy, collect_list, StringIndexer, OneHotEncoder, CountVectorizer, VectorAssembler, Normalizer, and filter.