Woah sick

In [1]:
!pip install pyspark pyarrow

WARNING: The directory '/home/jovyan/.cache/pip' or its parent directory is not owned or is not writable by the current user. The cache has been disabled. Check the permissions and owner of that directory. If executing pip with sudo, you should use sudo's -H flag.
Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: pyspark in /usr/local/spark/python (3.5.0)
Requirement already satisfied: pyarrow in /opt/conda/lib/python3.11/site-packages (13.0.0)
Requirement already satisfied: py4j==0.10.9.7 in /home/tragus/.local/lib/python3.11/site-packages (from pyspark) (0.10.9.7)
Requirement already satisfied: numpy>=1.16.6 in /opt/conda/lib/python3.11/site-packages (from pyarrow) (1.24.4)

In [2]:
import os
print(os.getcwd())

/expanse/lustre/projects/uci157/tragus

In [3]:
from pyspark.sql import SparkSession
from pyspark.sql.types import StructType, StructField, IntegerType, StringType, LongType, DoubleType, FloatType
from pyspark.sql.functions import col, count, length,countDistinct, min as spark_min, max as spark_max,avg, stddev, approx_count_distinct

spark = (SparkSession.builder.appName("MusicBrainz").config("spark.driver.memory", "2g").config("spark.executor.memory", "18g").config('spark.executor.instances', 7).getOrCreate())

I saw on Piazza somebody was asking about the Spark Jobs UI, and apparently I was right that this is something distinct from the Expanse Jobs page. Apparently it's this-

Not sure how to get it to display the active number of tasks since it's not live

In [4]:
import requests
import pandas as pd

# Get the active Spark Context and URL
sc = spark.sparkContext
url = f"{sc.uiWebUrl}/api/v1/applications/{sc.applicationId}/executors"

# Fetch the executor data from the API
response = requests.get(url)
executors = response.json()

# Format into a readable DataFrame
spark_df = pd.DataFrame(executors)[['id', 'totalCores', 'maxMemory', 'activeTasks', 'isActive']]
spark_df['maxMemory_GB'] = (spark_df['maxMemory'] / (1024**3)).round(2)
spark_df

       id  totalCores   maxMemory  activeTasks  isActive  maxMemory_GB
0  driver           8  1099746508            0      True          1.02

In [5]:
MBDUMP = "musicbrainz_project/raw_data/mbdump"

In [6]:
def peek(df, n=3):
    return display(df.limit(n).toPandas())

# DEFINE SCHEMAS

In [7]:
artist_schema = StructType([
    StructField("id",               IntegerType(),   True),
    StructField("gid",              StringType(),    True),
    StructField("name",             StringType(),    True),
    StructField("sort_name",        StringType(),    True),
    StructField("begin_date_year",  IntegerType(),   True),
    StructField("begin_date_month", IntegerType(),   True),
    StructField("begin_date_day",   IntegerType(),   True),
    StructField("end_date_year",    IntegerType(),   True),
    StructField("end_date_month",   IntegerType(),   True),
    StructField("end_date_day",     IntegerType(),   True),
    StructField("type",             IntegerType(),   True),
    StructField("area",             IntegerType(),   True),
    StructField("gender",           IntegerType(),   True),
    StructField("comment",          StringType(),    True),
    StructField("edits_pending",    IntegerType(),   True),
    StructField("last_updated",     StringType(),    True),
    StructField("ended",            StringType(),    True),
    StructField("begin_area",       IntegerType(),   True),
    StructField("end_area",         IntegerType(),   True),
])
instrument_schema = StructType([
    StructField("id",            IntegerType(), True),
    StructField("gid",           StringType(),  True),
    StructField("name",          StringType(),  True),
    StructField("type",          IntegerType(), True),
    StructField("edits_pending", IntegerType(), True),
    StructField("last_updated",  StringType(),  True),
])
label_schema = StructType([
    StructField("id",                IntegerType(), True),
    StructField("gid",               StringType(),  True),
    StructField("name",              StringType(),  True),
    StructField("begin_date_year",   IntegerType(), True),
    StructField("begin_date_month",  IntegerType(), True),
    StructField("begin_date_day",    IntegerType(), True),
    StructField("end_date_year",     IntegerType(), True),
    StructField("end_date_month",    IntegerType(), True),
    StructField("end_date_day",      IntegerType(), True),
    StructField("label_code",        IntegerType(), True),
    StructField("type",              IntegerType(), True),
    StructField("area",              IntegerType(), True),
    StructField("comment",           StringType(),  True),
    StructField("edits_pending",     IntegerType(), True),
    StructField("last_updated",      StringType(),  True),
    StructField("ended",             StringType(),  True),
])
genre_schema = StructType([
    StructField("id",            IntegerType(), True),
    StructField("gid",           StringType(),  True),
    StructField("name",          StringType(),  True),
    StructField("comment",       StringType(),  True),
    StructField("edits_pending", IntegerType(), True),
    StructField("last_updated",  StringType(),  True),
])
area_schema = StructType([
    StructField("id",            IntegerType(), True),
    StructField("gid",           StringType(),  True),
    StructField("name",          StringType(),  True),
    StructField("type",          IntegerType(), True),
    StructField("comment",       StringType(),  True),
    StructField("edits_pending", IntegerType(), True),
    StructField("last_updated",  StringType(),  True),
])
tag_schema = StructType([
    StructField("id",            IntegerType(), True),
    StructField("name",          StringType(),  True),
    StructField("ref_count",     IntegerType(), True),
])
gender_schema = StructType([
    StructField("id",   IntegerType(), True),
    StructField("name", StringType(),  True),
])
release_group_schema = StructType([
    StructField("id",            IntegerType(), True),
    StructField("gid",           StringType(),  True),
    StructField("name",          StringType(),  True),
    StructField("artist_credit", IntegerType(), True),
    StructField("type",          IntegerType(), True),
    StructField("comment",       StringType(),  True),
    StructField("edits_pending", IntegerType(), True),
    StructField("last_updated",  StringType(),  True),
])
l_artist_label_schema = StructType([
    StructField("id",        IntegerType(), True),
    StructField("link",      IntegerType(), True),
    StructField("entity0",   IntegerType(), True),  # artist
    StructField("entity1",   IntegerType(), True),  # label
])
l_artist_release_group_schema = StructType([
    StructField("id",        IntegerType(), True),
    StructField("link",      IntegerType(), True),
    StructField("entity0",   IntegerType(), True),  # artist
    StructField("entity1",   IntegerType(), True),  # release_group
])
label_tag_schema = StructType([
    StructField("label", IntegerType(), True),
    StructField("tag",   IntegerType(), True),
    StructField("count", IntegerType(), True),
])
l_artist_genre_schema = StructType([
    StructField("id",             IntegerType(), True),
    StructField("link",           IntegerType(), True),
    StructField("entity0",        IntegerType(), True),  # artist
    StructField("entity1",        IntegerType(), True),
])
l_artist_artist_schema = StructType([
    StructField("id",      IntegerType(), True),
    StructField("link",    IntegerType(), True),
    StructField("entity0", IntegerType(), True),
    StructField("entity1", IntegerType(), True),
])
release_group_tag_schema = StructType([
    StructField("release_group", IntegerType(), True),
    StructField("tag",           IntegerType(), True),
    StructField("count",         IntegerType(), True),
])
artist_tag_schema = StructType([
    StructField("artist", IntegerType(), True),
    StructField("tag",    IntegerType(), True),
    StructField("count",  IntegerType(), True),
])
artist_credit_schema = StructType([
    StructField("id",         IntegerType(), True),
    StructField("name",       StringType(),  True),
    StructField("artist_count", IntegerType(), True),
])
artist_credit_name_schema = StructType([
    StructField("artist_credit", IntegerType(), True),
    StructField("position",      IntegerType(), True),
    StructField("artist",        IntegerType(), True),
    StructField("name",          StringType(),  True),
    StructField("join_phrase",   StringType(),  True),
])
l_artist_instrument_schema = StructType([
    StructField("id",             IntegerType(), True),
    StructField("link",           IntegerType(), True),
    StructField("entity0",        IntegerType(), True),  # artist
    StructField("entity1",        IntegerType(), True),  # instrument
    StructField("edits_pending",  IntegerType(), True),
    StructField("last_updated",   StringType(),  True),
    StructField("link_order",     IntegerType(), True),
    StructField("entity0_credit", StringType(),  True),
    StructField("entity1_credit", StringType(),  True),
])

So the schema definitely aren't perfect - after testing out some SQL queries it becomes clear some of variables aren't assigned to the right columns. I think it will take some trial and error to suss out which variables are assigned correctly. It's a really great start though!! I've adjusted a couple and I'll spend a little more time experimenting with SQL to improve it

Something to be aware of is that a lot of these schema don't have all of the columns present in the TSV. We can still create the dataframes bc if there are extra columns without assignment in the schema, Spark just ignores them. Usually the variables we care about appear in the first half of the dataframe so ... maybe not so important but just FYI

# BUILD TABLES

In [8]:
schemas = {
    "artist": artist_schema,
    "instrument": instrument_schema,
    "label": label_schema,
    "genre": genre_schema,
    "area": area_schema,
    "tag": tag_schema,
    "gender": gender_schema,
    "release_group": release_group_schema,
    "l_artist_label": l_artist_label_schema,
    "l_artist_release_group": l_artist_release_group_schema,
    "label_tag": label_tag_schema,
    "l_artist_genre": l_artist_genre_schema,
    "l_artist_artist": l_artist_artist_schema,
    "release_group_tag": release_group_tag_schema,
    "artist_tag": artist_tag_schema,
    "artist_credit": artist_credit_schema,
    "artist_credit_name": artist_credit_name_schema,
    "l_artist_instrument": l_artist_instrument_schema,
}

dfs = {}
profile_rows = []

for table_name, schema in schemas.items():
    df = (
        spark.read
        .option("sep", "\t")
        .option("nullValue", r"\N")
        .option("header", "false")
        .option("quote", "")
        .option("escape", "")
        .schema(schema)
        .csv(f"{MBDUMP}/{table_name}")
    )

    dfs[table_name] = df

    print(f"=== PEEK: {table_name} ===")
    peek(df)

=== PEEK: artist ===

,id,gid,name,sort_name,begin_date_year,begin_date_month,begin_date_day,end_date_year,end_date_month,end_date_day,type,area,gender,comment,edits_pending,last_updated,ended,begin_area,end_area
0,2252039,fadeb38c-833f-40bc-9d8c-a6383b38b1be,Доктор Сатана,Доктор Сатана,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None,0,2021-11-23 07:08:52.479537+00,f,NaN,NaN
1,371203,49add228-eac5-4de8-836c-d75cde7369c3,Pete Moutso,"Moutso, Pete",NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN,NaN,None,0,None,f,NaN,NaN
2,3087346,dfdce491-133d-4e9f-9e48-795587e181b0,UNlT,UNlT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None,0,2025-09-14 23:53:28.004798+00,f,NaN,NaN

=== PEEK: instrument ===

,id,gid,name,type,edits_pending,last_updated
0,687,c1dbb66d-2356-417a-81ad-f688fee33257,guitarrón mexicano,2,0,2015-02-15 07:32:32.570132+00
1,695,2474c241-d267-433a-a404-688b13c51d11,jouhikko,2,0,2015-02-25 19:47:04.610414+00
2,701,c0cc863c-ea65-4b8a-b365-28b81b72d846,friction idiophone,3,0,2015-02-26 10:28:49.766548+00

=== PEEK: label ===

,id,gid,name,begin_date_year,begin_date_month,begin_date_day,end_date_year,end_date_month,end_date_day,label_code,type,area,comment,edits_pending,last_updated,ended
0,1,f43e252d-9ebf-4e8e-bba8-36d080756cc1,Deleted Label,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None,0,None,f
1,2,39c4dc0c-badb-4ac3-b810-e4f374dff6d9,Certificate 18,NaN,NaN,NaN,NaN,NaN,NaN,2592.0,4.0,221.0,None,0,None,f
2,103730,6f70a5cb-99a7-4a42-9208-412446d4aa0f,Flo Master Inc.,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4.0,222.0,None,0,2015-05-18 20:41:54.551166+00,f

=== PEEK: genre ===

,id,gid,name,comment,edits_pending,last_updated
0,1,54c01942-22fd-4184-9877-1db0089b18f1,acid house,None,0,2019-05-13 17:46:28.122726+00
1,2,7dc2b20f-3953-4874-b9bf-41b8ba06d20c,acid jazz,None,0,2019-05-13 17:46:28.122726+00
2,3,ba64013e-27bb-4f14-a530-8d25b296e0da,acid techno,None,0,2019-05-13 17:46:28.122726+00

=== PEEK: area ===

,id,gid,name,type,comment,edits_pending,last_updated
0,15449,2913ad77-cec8-4d2f-98d3-d4aa46ab73bc,Greccio,4,0,NaN,None
1,38,71bbafaa-e825-3e15-8ca9-017dcad1748b,Canada,1,0,NaN,None
2,43,82d5f4d6-aed4-3ff5-81d1-5363ac6e97a7,Chile,1,0,NaN,None

=== PEEK: tag ===

       id           name  ref_count
0  250930       italopop          1
1  246528      champ 700          1
2  246456  es war einmal          1

=== PEEK: gender ===

   id            name
0   2          Female
1   1            Male
2   4  Not applicable

=== PEEK: release_group ===

,id,gid,name,artist_credit,type,comment,edits_pending,last_updated
0,1964563,f59da930-70ba-4992-a346-7ed2d8e3cda8,Wande,627364,1,None,0,2018-04-30 23:56:50.245482+00
1,2666236,1cf5c673-171c-41fe-abfd-27a455013bbd,À nous,2966520,1,None,0,2021-04-22 19:12:59.273077+00
2,13,0eac6659-d590-3eb7-8c13-ed8b3fdf4ef7,The Inevitable,11,1,None,0,2009-05-24 20:47:00.490177+00

=== PEEK: l_artist_label ===

   id   link  entity0  entity1
0   1  12132   473113    16028
1   2  12132   474797    16278
2   3  12132   289759    16522

=== PEEK: l_artist_release_group ===

   id  link  entity0  entity1
0   1    47   162235   612285
1   2   101   471908   707628
2   4    47   469841   650261

=== PEEK: label_tag ===

    label  tag  count
0  241710  235      1
1  171313    7      1
2  256852  303      1

=== PEEK: l_artist_genre ===

   id     link  entity0  entity1
0   1  1117609    34423       94
1  81  1117609  3221251       86
2  82  1117609   435717       15

=== PEEK: l_artist_artist ===

   id  link  entity0  entity1
0   1  6337   475809   287770
1   3  6338   238828     3184
2   6  6337   367163   493186

=== PEEK: release_group_tag ===

   release_group   tag  count
0        1835483  1409      1
1         445144    11      1
2        3413902   564      1

=== PEEK: artist_tag ===

    artist  tag  count
0  2447565  523      1
1  2337807  204      1
2  2734633   55      1

=== PEEK: artist_credit ===

        id                                               name  artist_count
0  4229350  Jean-Paul Fouchécourt, Yvonne Naef, Saito Kine...             4
1  3320885                                          The Turns             1
2  3320887                                           Son.Sine             1

=== PEEK: artist_credit_name ===

   artist_credit  position  artist                    name join_phrase
0         578352         0  578352           Gustav Ruppke        None
1         273232         0  273232                 Zachary        None
2         153193         0  153193  The High Level Ranters        None

=== PEEK: l_artist_instrument ===

,id,link,entity0,entity1,edits_pending,last_updated,link_order,entity0_credit,entity1_credit
0,1,311992,1218252,121,0,2016-08-01 11:22:19.207793+00,0,None,None
1,2,312066,1395197,19,0,2016-08-01 14:14:07.499778+00,0,None,None
2,24,393478,1261488,808,0,2017-05-31 08:31:04.355584+00,0,None,None

# FOREIGN KEY MAP (for navigating the database)

In [9]:
foreign_key_map = {
    "artist": {
        "type":       ("artist_type", "id"),
        "area":       ("area", "id"),
        "gender":     ("gender", "id"),
        "begin_area": ("area", "id"),
        "end_area":   ("area", "id"),
    },
    "instrument": {
        "type": ("instrument_type", "id"),
    },
    "label": {
        "type": ("label_type", "id"),
        "area": ("area", "id"),
    },
    "release_group": {
        "type":          ("release_group_primary_type", "id"),
        "artist_credit": ("artist_credit", "id"),
    },
    "artist_credit_name": {
        "artist_credit": ("artist_credit", "id"),
        "artist":        ("artist", "id"),
    },
    "label_tag": {
        "label": ("label", "id"),
        "tag":   ("tag", "id"),
    },
    "artist_tag": {
        "artist": ("artist", "id"),
        "tag":    ("tag", "id"),
    },
    "release_group_tag": {
        "release_group": ("release_group", "id"),
        "tag":           ("tag", "id"),
    },
    "l_artist_genre": {
        "link":    ("link", "id"),
        "entity0": ("artist", "id"),
        "entity1": ("genre", "id"),
    },
    "l_release_group_genre": { 
        "link":    ("link", "id"),
        "entity0": ("release_group", "id"),
        "entity1": ("genre", "id"),
    },
    "l_artist_label": {
        "link":    ("link", "id"),
        "entity0": ("artist", "id"),
        "entity1": ("label", "id"),
    },
    "l_artist_release_group": {
        "link":    ("link", "id"),
        "entity0": ("artist", "id"),
        "entity1": ("release_group", "id"),
    },
    "l_artist_artist": {
        "link":    ("link", "id"),
        "entity0": ("artist", "id"),
        "entity1": ("artist", "id"),
    },
    "l_artist_instrument": {
        "link":    ("link", "id"),
        "entity0": ("artist", "id"),
        "entity1": ("instrument", "id"),
    },
}

Great work on the map! I just removed "artist_genre" and "release_group_genre" because I couldn't find those tables in the database. But I'm pretty sure it's correct

# TESTING SOME BASIC SQL QUERIES

Here are some cool queries

In [10]:
for table_name, df in dfs.items():
    df.createOrReplaceTempView(table_name)

In [11]:
def peek(df, n=20):
    return display(df.limit(n).toPandas())

***

1) Select all from artist

In [12]:
peek(spark.sql("""
    SELECT *
    FROM artist
"""))

,id,gid,name,sort_name,begin_date_year,begin_date_month,begin_date_day,end_date_year,end_date_month,end_date_day,type,area,gender,comment,edits_pending,last_updated,ended,begin_area,end_area
0,2252039,fadeb38c-833f-40bc-9d8c-a6383b38b1be,Доктор Сатана,Доктор Сатана,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None,0,2021-11-23 07:08:52.479537+00,f,NaN,NaN
1,371203,49add228-eac5-4de8-836c-d75cde7369c3,Pete Moutso,"Moutso, Pete",NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN,NaN,None,0,None,f,NaN,NaN
2,3087346,dfdce491-133d-4e9f-9e48-795587e181b0,UNlT,UNlT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None,0,2025-09-14 23:53:28.004798+00,f,NaN,NaN
3,2851271,165a49a0-2b3b-4078-a3c1-905afdc07c0a,Babyglock,Babyglock,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None,0,2024-10-19 03:33:55.474151+00,f,NaN,NaN
4,145773,7b4a548e-a01a-49b7-82e7-b49efeb9732c,Aric Leavitt,"Leavitt, Aric",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None,0,None,f,NaN,NaN
5,1076328,60aca66f-e91a-4cb5-9308-b6e293cd833e,Fonograff,Fonograff,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None,0,2014-01-10 16:25:20.992213+00,f,NaN,NaN
6,1172876,3e1bd546-d2a7-49cb-b38d-d70904a1d719,Al Street,"Street, Al",NaN,NaN,NaN,NaN,NaN,NaN,1.0,222.0,1.0,None,0,2014-11-23 14:07:19.782509+00,f,NaN,NaN
7,220155,df120895-f6c6-4a66-b9cf-73350f0beb61,Love .45,Love .45,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None,0,None,f,NaN,NaN
8,618464,c14f8d3f-ee81-416f-800f-8eff7e77a2e1,Sintellect,Sintellect,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None,0,2009-05-23 09:41:53.269195+00,f,NaN,NaN
9,285714,b68a3969-319a-462f-942b-cd35581414fc,Evie Tamala,Evie Tamala,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None,0,None,f,NaN,NaN
10,886708,2c8ae2e0-3934-440e-81f5-2ec7fd0d7899,Jean-Pierre Martin,"Martin, Jean-Pierre",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None,0,2012-04-22 19:01:53.69375+00,f,NaN,NaN
11,209107,ac63d693-7b24-4258-a3db-09743b1b4269,Deejay One,Deejay One,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None,0,None,f,NaN,NaN
12,388372,4c4b7c6f-9285-4d6a-bc10-e5c9e08045f8,wecamewithbrokenteeth,wecamewithbrokenteeth,NaN,NaN,NaN,NaN,NaN,NaN,2.0,NaN,NaN,None,0,None,f,NaN,NaN
13,726151,055f435f-dba6-4156-9050-6ac41113e45f,The Blackbelt Band,"Blackbelt Band, The",NaN,NaN,NaN,NaN,NaN,NaN,2.0,NaN,NaN,None,0,2010-06-22 04:37:31.770468+00,f,NaN,NaN
14,152659,ab1b631b-9896-4433-bef9-7868bf8a42f3,Giant Tomo,Giant Tomo,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None,0,None,f,NaN,NaN
15,3156789,da7fc031-5814-45fd-aa61-873390c6c543,OGU,OGU,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Japanese reggae singer,0,2025-12-14 23:01:35.661855+00,f,NaN,NaN
16,2064913,1fbb9556-b647-498a-a8ed-d3b5e8d7f85c,Tobias Lorsbach,"Lorsbach, Tobias",NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN,1.0,None,0,2020-10-29 11:32:33.065895+00,f,NaN,NaN
17,1000880,e6895f6e-f636-4ff6-b406-f5ddaf6cb243,Diskobitch,Diskobitch,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None,0,2013-04-25 00:05:28.234204+00,f,NaN,NaN
18,471075,4eee2c60-c2c8-4b33-b14f-0eed4bf4d11a,Seanews,Seanews,2001.0,NaN,NaN,NaN,NaN,NaN,2.0,NaN,NaN,None,0,None,f,NaN,NaN
19,98827,302d69b6-4ed9-48ec-b6dd-1c70e765b327,CyberDog,CyberDog,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None,0,None,f,NaN,NaN

***

2. Select all artists and their labels

In [13]:
peek(spark.sql("""
    SELECT a.name AS artist_name, l.name AS label
    FROM l_artist_label lal
    JOIN artist a ON lal.entity0 = a.id
    JOIN label l ON lal.entity1 = l.id
"""))

            artist_name                              label
0                s'Poom                Legendaarne Records
1            Guido Elmi                              Nopop
2         Marco Resmann                           Upon.You
3   Karl-Jonas Winqvist                Sing a Song Fighter
4          Stuart Brown             British Film Institute
5            Earl Young  Baker, Harris & Young Productions
6          Alexia Coley                   Jalapeno Records
7         Darren Hickey                          Xpressive
8         Darren Hickey                      Juice Records
9          Ras Sheehama                African Cream Music
10     Guadalupe Pineda                         InterSound
11       Gavin Hardkiss                           Hardkiss
12               Whitey                             Spoilt
13               Whitey                          NO! Label
14               Escala                         Syco Music
15      Robbie Hardkiss                           Hardkiss
16          Christafari                      Gotee Records
17         Samsun Demir                Doğan Music Company
18       Fred Henderson        Henderson Music Productions
19        The Svengalis                Villains and Rogues

***

3. Number of release groups per artist sorted by most prolific

In [14]:
peek(spark.sql("""
    SELECT a.name AS artist_name, COUNT(rg.id) AS release_group_count
    FROM release_group rg
    JOIN artist_credit_name acn ON rg.artist_credit = acn.artist_credit
    JOIN artist a ON acn.artist = a.id
    GROUP BY a.name
    ORDER BY release_group_count DESC
"""))

                  artist_name  release_group_count
0             Various Artists               281842
1        Ludwig van Beethoven                 6088
2       Johann Sebastian Bach                 6011
3     Wolfgang Amadeus Mozart                 5922
4                   [unknown]                 3432
5             Johannes Brahms                 2946
6              Franz Schubert                 2852
7       Пётр Ильич Чайковский                 2684
8             Antonio Vivaldi                 2143
9           Bruce Springsteen                 2127
10            Fryderyk Chopin                 2008
11  London Symphony Orchestra                 1963
12               Joseph Haydn                 1959
13            Robert Schumann                 1959
14                  Zippy Kid                 1941
15           Armin van Buuren                 1938
16         The Rolling Stones                 1897
17     George Frideric Handel                 1740
18             Antonín Dvořák                 1676
19             user-177606669                 1654

***

4. Number of labels per country

In [15]:
peek(spark.sql("""
    SELECT a.name as area, COUNT(l.id) as label_count
    FROM label l
    JOIN area a ON l.area = a.id
    GROUP BY a.name
    ORDER BY label_count DESC
    LIMIT 20
"""))

              area  label_count
0    United States        30680
1   United Kingdom        14758
2            Japan        12059
3          Germany         9388
4           France         5974
5            Italy         4110
6           Canada         3227
7           Sweden         2933
8      Netherlands         2893
9            Spain         2345
10          London         2341
11       Australia         2231
12          Russia         1868
13         Finland         1843
14        New York         1704
15         Belgium         1656
16     South Korea         1629
17          Berlin         1320
18          Brazil         1317
19          Norway         1269

***

5. Number of artists by gender

In [20]:
peek(spark.sql("""
    SELECT g.name AS gender, COUNT(*) AS count
    FROM artist a
    JOIN gender g ON a.gender = g.id
    GROUP BY g.name
    ORDER BY count DESC
"""))

           gender   count
0            Male  932192
1          Female  280203
2  Not applicable    2443
3      Non-binary    2237
4           Other    1787